### ISSUE TITLE
Might just be an idiot, but issues installing and using

### ISSUE THREAD

**Issue by xtotallyxlegitx** [continue-revolution/sd-webui-animatediff#1]
I installed from url (https://github.com/continue-revolution/sd-webui-animatediff) and the animatediff box appears in my txt2img tab, but when I try to run it, it generates an image, but it's not a smooth gif like the examples, instead it's just a fast slideshow of numerous different gens. When trying again, it says no model. I manually downloaded the SDv15 ckpt but there's no sd-webui-animatediff/model/ folder anywhere.

**Comment by continue-revolution** [comment]
Please download model from https://drive.google.com/drive/folders/1EqLC65eR1-W-sGD0Im7fkED6c8GkiNFI and put weights under sd-webui-animatediff/model/. You should manually create a model folder under the webui/extension/SS-webui-animatediff directory.

**Comment by xtotallyxlegitx** [comment]
> Please download model from https://drive.google.com/drive/folders/1EqLC65eR1-W-sGD0Im7fkED6c8GkiNFI and put weights under sd-webui-animatediff/model/. You should manually create a model folder under the webui/extension/SS-webui-animatediff directory.

This did it and was all it needed. Thanks!
