### ISSUE TITLE
[Feature]: Doesn't work on img2img panel

### ISSUE THREAD

**Issue by miibotree** [continue-revolution/sd-webui-animatediff#10]
When I use img2img with AnimateDiff check-box enabled, it seems the AnimateDiff module are not in effect.
Neither the log shows any thing about the AnimateDiff Module, nor the AnimateDiff directory appears.

**Comment by continue-revolution** [comment]
It works on my side. Will close this issue at this time and add a sample on README

**Comment by ykk648** [comment]
check https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448, it's extensions conflict
