### ISSUE TITLE
[Feature]: Improved generation outside of DDIM

### ISSUE THREAD

**Issue by taka-0770** [continue-revolution/sd-webui-animatediff#103]
### Expected behavior

If you generate it using something other than DDIM, it will take around 5 minutes to generate, but scenes may change, and 16 images may be displayed in an instant.
Wouldn't it be possible to generate something other than DDIM that is equivalent to DDIM?
By the way, in my environment it takes over an hour with DDIM. When generated with DPM++2M SDE Karras, even 512x768 can be generated within 5 minutes.

**Comment by continue-revolution** [comment]
Yes, you can use whatever sampler you like, and as long as your prompt is good, you will get descent gif.
