### ISSUE TITLE
[Bug]: with and without AnimateDiff use, the image is different with the same setting and seed

### ISSUE THREAD

**Issue by xyzDist** [continue-revolution/sd-webui-animatediff#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

not sure if this is a bug, if I use animateDiff on and off, the images is compeletely differen in t2i even the same setting and seed.
is this normal?

Thanks!

### Steps to reproduce the problem

1. gen without animateDiff
2. gen with animateDiff
3. compare the both images

### What should have happened?

expected to be the same at first frame

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
/
```

### Console logs

```Shell
/
```

**Comment by continue-revolution** [comment]
This is normal, because the model architecture is very different. This extension will insert several transformers into the UNet.
