### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by asvan-o** [continue-revolution/sd-webui-animatediff#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

animation diff diff in webui 1.5/1.52/1.6 version

-----------------------------------------------
Please answer me if there is anything I am mistaken about.

### Steps to reproduce the problem

1. Go to ....  webui
2. Press ....
3. ...

### What should have happened?

Animationdiff extension shall be displayed on the webui.

### Commit where the problem happens

webui: 1.5/1.52/1.6
extension: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Error message:
Error loading script: animate.py
Tracking (last of most recent calls):
파일 "D:\Stable Diffusion AI\Stable-Diffusion-webui-1.5.0\modules\scripts.py ", line 295, load_
script_module = script_loading.load_module(scriptfile.path)
load_module의 10행 "D:\Stable Diffusion AI\stable-diffusion-webui-1.5.0\modules\script_loading.py" 파일
module_spec.loader.exec_module(module)
파일 "<frozen importlib._bootstrap_external>", 행 883, exec_module
파일 "<frozen import lib._bootstrap>", 행 241, _call_with_frames_removed
<module>의 9행 "D:\Stable Diffusion AI\stable-Diffusion-webui-1.5.0\extensions\AnimateDiff\scripts\animate.py " 파일
importation of diffusers
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by continue-revolution** [comment]
You are installing the original repo, which is a stand alone software, not an extension.
