### ISSUE TITLE
[Question]: `Remove Head` and `Remove Tail` instructions ?

### ISSUE THREAD

**Issue by AugmentedRealityCat** [continue-revolution/sd-webui-animatediff#112]
I would like to know what is the exact function of the "remove tail" and "remove head" checkboxes, and have some basic instructions on how to use them properly.

**Comment by continue-revolution** [comment]
You get a list (A) of images and my code combine them to a gif. By checking “add reverse), list A become A + A.reverse(). If you generate a gif with 4 frames, A is [1, 2, 3, 4] and A + A.reverse() is [1, 2, 3, 4, 4, 3, 2, 1]. “Remove head” make this list become [1, 2, 3, 4, 4, 3, 2] and “remove tail” make it [1, 2, 3, 4, 3, 2, 1]. If you check both, it become [1, 2, 3, 4, 3, 2]. Hope this helps.

**Comment by AugmentedRealityCat** [comment]
Perfectly clear ! Thank you.

In other words, it removes duplicate frames.
