### ISSUE TITLE
[Bug]: i2i last_frame error

### ISSUE THREAD

**Issue by aiden-cupist** [continue-revolution/sd-webui-animatediff#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

when i submit a last frame at i2i, I get the following error

```
*** Error running before_process_batch: /home/ubuntu/stable-diffusion-webui/extensions/sd-webui-animatedi
ff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/home/ubuntu/stable-diffusion-webui/modules/scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py",
line 44, in before_process_batch
        AnimateDiffI2VLatent().randomize(p, params)
      File "/home/ubuntu/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_latent.py", line 30, in randomize
        for i in range(params.last_frame)
    TypeError: only integer scalar arrays can be converted to a scalar index
```

this is the code where the error occurs (animated_latent.py line 26 ~ 37)

```
if params.last_frame is not None:
            # Get last_alpha
            last_alpha = [
                1 - pow(i, params.latent_power_last) / params.latent_scale_last
                for i in range(params.last_frame)
            ]
            last_alpha.reverse()
            logger.info(f"Randomizing last_latent according to {init_alpha}.")
            last_alpha = torch.tensor(last_alpha, dtype=torch.float32, device=device)[
                :, None, None, None
            ]
            last_alpha[last_alpha < 0] = 0
```

### Steps to reproduce the problem

1. Submit last frame at i2i
2. just process
3. error occurs at terminal (the output gif is generated without problem, but it does not reflect the last frame)

### What should have happened?

no error in terminal

### Commit where the problem happens

webui: 1.6
extension: latest [c28eb5df]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--share --enable-insecure-extension-access --xformers --xformers-flash-attention --opt-channelslast --api
```

### Console logs

```Shell
there is no error at browser console
```

**Comment by continue-revolution** [comment]
In what format do you submit your last frame to webui via api?

**Comment by aiden-cupist** [comment]
I submit my last frame via webui GUI not api.
and its format is '.png'

**Comment by zopi4k** [comment]
Same problem ...
`*** Error running before_process_batch: D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 43, in before_process_batch
        AnimateDiffI2VLatent().randomize(p, params)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_latent.py", line 31, in randomize
        for i in range(params.last_frame)
    TypeError: only integer scalar arrays can be converted to a scalar index`

**Comment by zappityzap** [comment]
This makes the errors go away, but the resulting animation looks wrong. It starts as the init image, and then adds more and more latent noise.
```diff
diff --git a/scripts/animatediff_latent.py b/scripts/animatediff_latent.py
index c0a3b0e..80a32ba 100644
--- a/scripts/animatediff_latent.py
+++ b/scripts/animatediff_latent.py
@@ -1,4 +1,6 @@
 import torch
+import numpy as np
+from PIL import Image
 from modules import images, shared
 from modules.devices import device, dtype_vae, torch_gc
 from modules.processing import StableDiffusionProcessingImg2Img
@@ -28,7 +30,7 @@ class AnimateDiffI2VLatent:
             # Get last_alpha
             last_alpha = [
                 1 - pow(i, params.latent_power_last) / params.latent_scale_last
-                for i in range(params.last_frame)
+                for i in range(params.video_length)
             ]
             last_alpha.reverse()
             logger.info(f"Randomizing last_latent according to {init_alpha}.")
@@ -48,8 +50,10 @@ class AnimateDiffI2VLatent:
             last_frame = params.last_frame
             if p.resize_mode != 3:
                 last_frame = images.resize_image(
-                    p.resize_mode, last_frame, p.width, p.height
-                )[None, ...]
+                    p.resize_mode, Image.fromarray(last_frame), p.width, p.height
+                )
+                last_frame = np.asarray(last_frame)
+                last_frame = last_frame.transpose(2, 0, 1)[None, ...]
             last_frame = torch.from_numpy(last_frame).to(device).to(dtype_vae)
             last_latent = images_tensor_to_samples(
                 last_frame,
@@ -68,7 +72,7 @@ class AnimateDiffI2VLatent:
             # Modify init_latent
             p.init_latent = (
                 p.init_latent * init_alpha
-                + p.last_latent * last_alpha
+                + last_latent * last_alpha
                 + p.rng.next() * (1 - init_alpha - last_alpha)
             )
         else:
```

**Comment by continue-revolution** [comment]
seems like I made some very silly mistake. Will be fixed later.

**Comment by continue-revolution** [comment]
You can post some init and last image if you want, better anime than realistic human

**Comment by continue-revolution** [comment]
you should be able to run last frame, but it seems that it's not easy to control last frame in this way... you are welcome to shoot a new issue. things might get much better when CN is supported later.

**Comment by aiden-cupist** [comment]
Thanks! 🥹😀
