### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'imageio.v3'

### ISSUE THREAD

**Issue by yebkamin** [continue-revolution/sd-webui-animatediff#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I start sd with the webui-user bat file. It loads but has this error in regards to animatedif:

** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "C:\Users\trevo\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\trevo\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\trevo\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 11, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "C:\Users\trevo\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 3, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'

I have tried reinstalling SD and Animatediff but nothing seems to work. I have seen other sources mention needing to run something with pip. I have tried that but i'm not sure if i'm missing a step here. 

### Steps to reproduce the problem

sd with the webui-user bat file. 
Check Cmd prompt to see error 

### What should have happened?

Stable diffusion should load with animatediff as an extension

### Commit where the problem happens

webui: v.1.6.0
extension: 99bcb53d

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --medvram
git switch release_candidate
git pull
call webui.bat
```

### Console logs

```Shell
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "C:\Users\trevo\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\trevo\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\trevo\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 11, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "C:\Users\trevo\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 3, in <module>
        import imageio.v3 as imageio
    ModuleNotFoundError: No module named 'imageio.v3'
```

**Comment by zappityzap** [comment]
Try one or all of these:
```
pip install imageio
pip install imageio[ffmpeg]
pip install imageio[pyav]
```

**Comment by HelloJessicaM** [comment]
I'm having this issue too, tried all the pip install above. It's still having the same error. 

```
C:\Users\User>pip install imageio[ffmpeg]
Requirement already satisfied: imageio[ffmpeg] in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.31.3)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from imageio[ffmpeg]) (1.24.2)
Requirement already satisfied: pillow>=8.3.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from imageio[ffmpeg]) (9.4.0)
Collecting imageio-ffmpeg (from imageio[ffmpeg])
  Obtaining dependency information for imageio-ffmpeg from https://files.pythonhosted.org/packages/c6/01/716106099e48c4f419876d5814679a94dd7d6f441217c97c1b608123c6bb/imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl.metadata
  Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl.metadata (1.7 kB)
Collecting psutil (from imageio[ffmpeg])
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Requirement already satisfied: setuptools in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from imageio-ffmpeg->imageio[ffmpeg]) (63.2.0)
Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl (22.6 MB)
Installing collected packages: psutil, imageio-ffmpeg
Successfully installed imageio-ffmpeg-0.4.9 psutil-5.9.5

C:\Users\User>pip install imageio[pyav]
Requirement already satisfied: imageio[pyav] in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.31.3)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from imageio[pyav]) (1.24.2)
Requirement already satisfied: pillow>=8.3.2 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from imageio[pyav]) (9.4.0)
Collecting av (from imageio[pyav])
  Using cached av-10.0.0-cp310-cp310-win_amd64.whl (25.3 MB)
Installing collected packages: av
Successfully installed av-10.0.0
```

**Comment by continue-revolution** [comment]
@HelloJessicaM activate your webui virtual environment first

**Comment by kaosbeat** [comment]
Hi,

I activated my venv by running `source venv/bin/activate`from the stable diffusion webui directory

seeing the `(venv) `prepended to my prompt I ran the above mention pip commands. It did not help

only after running 

` pip install openpiv --upgrade --force-reinstall`

as mentioned here: https://github.com/OpenPIV/openpiv-python/issues/244

I got it to work. Be warned this gave some minor problems... in the end everything worked

**Comment by KenanHuang** [comment]
Try the following command,and the problem might be solved
`pip install --upgrade "imageio>=2.26"`

**Comment by AmigoBarba** [comment]
It says I don't have Imagio, but upon trying to install it, it says the already installed.
 "<module>
    import imageio
ModuleNotFoundError: No module named 'imageio'

Cannot import E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: No module named 'imageio'"

Tried:
pip install imageio
pip install imageio[ffmpeg]
pip install imageio[pyav]
pip install openpiv --upgrade --force-reinstall

What should I do?
