### ISSUE TITLE
[Feature]: Have optional interpolation & upscaling, like deforum

### ISSUE THREAD

**Issue by Mozoloa** [continue-revolution/sd-webui-animatediff#119]
### Expected behavior

Deforum has this neat little options where the end result can be interpolated with RIFE or FILM and you can also upscale using various models. It'd be fantastic to have such options upon generation.

Right now I reup the output to the deforum tab, but it would be great to have it as a checkbox.

I know it's probably a bit tricky to implement but it's a cool suggestion imo !

**Comment by ace2duce** [comment]
Totally need it please

**Comment by continue-revolution** [comment]
I'm happy to support this, but you have to be patient.
