### ISSUE TITLE
[Bug]: Installation not complete

### ISSUE THREAD

**Issue by wandrzej** [continue-revolution/sd-webui-animatediff#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I've installed the extension
I see AnimateDiff in settings, i have the option in the text2img and img2img panels
My Automatic instance didn't autodownload the motion modules - downloaded manually and put them in \extensions\sd-webui-animatediff\model

When I enable the AnimateDif, it just produces an image, no gif. No messages related to this extension in the console

Setup: W11 with xformers installed 

### Steps to reproduce the problem

Pretty much what I described
install from github link
download models

### What should have happened?

animated gif output

### Commit where the problem happens

webui: 1.4.1
extension: 

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
nothing at all apart from typical image generation progress
```

**Comment by continue-revolution** [comment]
1. update the extension to v1.1.0
2. check gradio output
3. check `stable-diffusion-webui/outputs/{txt2img or img2img}-images/{date}` and see how many image frames it generated.

**Comment by wandrzej** [comment]
Thanks for the suggestions, but I honestly need to open this up again
I'm on 88a04c32 version. From what I can tell that's the latest update in this repo
the extension link for release 1.1 in the readme leads to Segment Anything extension not AnimateDiff. So I'm a little bit confused, what do you mean to update this. 

<img width="753" alt="image" src="https://github.com/continue-revolution/sd-webui-animatediff/assets/26924000/a840d728-fa60-4e18-ab8e-1380d3ba5bb3">


regarding points 2 and 3, as I wrote I get nothing - it looks like creating an image, regardless if I turn the extension on or off.
