### ISSUE TITLE
animatediff not working [in SD.NEXT]: module 'modules.sd_hijack' has no attribute 'current_optimizer'

### ISSUE THREAD

**Issue by cibernicola** [continue-revolution/sd-webui-animatediff#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

All info here:
https://github.com/vladmandic/automatic/issues/2232

### Steps to reproduce the problem

https://github.com/vladmandic/automatic/issues/2232

### What should have happened?

Work

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
https://github.com/vladmandic/automatic/issues/2232
```

### Console logs

```Shell
https://github.com/vladmandic/automatic/issues/2232
```

### Additional information

https://github.com/vladmandic/automatic/issues/2232

**Comment by lebakerino** [comment]
Same issue. (Using latest update of SD.Next and Animediff)

**Comment by continue-revolution** [comment]
vlad probably does not support this

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_hijack.py#L38

you have 3 choices
1. go back to A1111 (recommended, I develop based on the latest A1111)
2. ask vlad to support this (there will potentially be future problems if I use a feature not present in vlad but in A1111)
3. revert back to a previous version of this extension via `git checkout v1.x.x` where 1.x.x is the version you desire
