### ISSUE TITLE
[Bug]: Inpainting?

### ISSUE THREAD

**Issue by vitacon** [continue-revolution/sd-webui-animatediff#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I could not find any information whether AnimateDiff could work with inpaiting and I get strange results.
The first frame looks fine but then it descends into chaos filling the whole masked region. It seem it somehow accumulates the noise...? Is it expected behaviour with the current state of the extension?

https://github.com/continue-revolution/sd-webui-animatediff/assets/58292841/4b8ee316-d553-4983-bcf7-04e92c24191f

### Steps to reproduce the problem

1. Go to Inpaint
2. Create any mask
3. Enable AnimateDiff
4. Generate something

### What should have happened?

I expected a meaningful frames.

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
no errors
```

**Comment by continue-revolution** [comment]
Previously it was not compatible with ControlNet and now it is. You can try and see what it goes. I will close this issue for now.
