### ISSUE TITLE
[Bug]: FILM interpolation not creating animation

### ISSUE THREAD

**Issue by ManOrMonster** [continue-revolution/sd-webui-animatediff#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Frame Interpolation creates extra frames but does not compile them into an animation. I am not using ControlNet, and I have a new installation of Deforum.

<img width="869" alt="image" src="https://github.com/continue-revolution/sd-webui-animatediff/assets/3925151/80eb3d80-6f9a-4db4-b6b3-fb82590ea54e">

### Steps to reproduce the problem

1. Click on FILM
2. Generate

### What should have happened?

It should have compiled the resultant frames into an animation.

### Commit where the problem happens

webui: 5ef669d
extension: 9a4dd73

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Total frames to FILM-interpolate: 16. Total frame-pairs: 15.
FILM progress: 100%|███████████████████████████████████████████████████████████████| 15/15 [00:09<00:00,  1.65it/s]
Interpolation done in 9.63 seconds!
*** Error running postprocess: C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "C:\stable-diffusion\automatic1111\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff.py", line 73, in postprocess
        AnimateDiffOutput().output(p, res, params)
      File "C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 34, in output
        video_paths += self._save(params, video_list, video_path_prefix, res, i)
      File "C:\stable-diffusion\automatic1111\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 148, in _save
        "scale": ("scale", f"{video_list[0].width}:{video_list[0].height}")
    AttributeError: 'numpy.ndarray' object has no attribute 'width'
```

**Comment by continue-revolution** [comment]
check Do not append detectmap to output in Settings/ControlNet and see what's going on.

**Comment by continue-revolution** [comment]
If you are not using ControlNet then maybe I'll pass this to the developer of this feature.

**Comment by continue-revolution** [comment]
alright, I don't think this is the problem of ControlNet. I'll pass this to @zappityzap

**Comment by zappityzap** [comment]
My apologies, I did not test the optimized GIF palette code path. I'll prepare a PR soon. Non-optimized GIF should still work.

This was caused by interpolation overwriting video_list with interpolated frames loaded from disk. This loses some of the attributes like .width, .height, and .info. I'm not sure if there's a better way to do it.
