### ISSUE TITLE
[Bug]: Not working, no module 'modules.sd_samplers_cfg_denoiser'

### ISSUE THREAD

**Issue by vrubzov1957** [continue-revolution/sd-webui-animatediff#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Not working in web-interface

Error in console:
`from scripts.animatediff_infv2v import AnimateDiffInfV2V File "D:\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 2, in <module> from modules.sd_samplers_cfg_denoiser import CFGDenoiser ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'`

### Steps to reproduce the problem

1. Go to Interface - there are no AnimateDiff
2. In console i see error when Automatic is started

### What should have happened?

Working AnimateDiff 

### Commit where the problem happens

webui: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c ?
extension: ?

### What browsers do you use to access the UI ?

Edge 117.0.2045.43 x64

### Command Line Arguments

```Shell
--opt-sdp-attention --listen --xformers --disable-safe-unpickle
```

### Console logs

```Shell
`from scripts.animatediff_infv2v import AnimateDiffInfV2V File "D:\stable-diffusion-portable-main\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 2, in <module> from modules.sd_samplers_cfg_denoiser import CFGDenoiser ModuleNotFoundError: No module named 'modules.sd_samplers_cfg_denoiser'`
```

**Comment by continue-revolution** [comment]
You should use 1.6.0. The next feature (infinite v2v) will hack CFGDenoiser.
