### ISSUE TITLE
[Feature]: Add tooltips to Stride and img2img items

### ISSUE THREAD

**Issue by Clonephaze** [continue-revolution/sd-webui-animatediff#149]
### Expected behavior

There are tooltip boxes for each item now, but I left Stride and img2img items blank as I don't really know how to explain them. I think stride controls how much motion but I wasn't sure, and I have no idea what the img2img items do at all. 

When you get a chance could you add info to their tooltips? Just making this as a way to ask since I didn't know where else to ask.

**Comment by continue-revolution** [comment]
It is almost impossible to explain precisely. They should read https://github.com/continue-revolution/sd-webui-animatediff#img2gif

**Comment by continue-revolution** [comment]
If they cannot understand this either, they should read the source code, or, ask GPT to explain source code for them.
