### ISSUE TITLE
[Bug]: Closed loop / Stride / Overlap doesen't works

### ISSUE THREAD

**Issue by zopi4k** [continue-revolution/sd-webui-animatediff#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

• 1 ] **Closed Loop**

I have try to make closed loop, I have read the README and folow the steps 

```
Closed loop —  If you enable this option and your number of frames is greater than your batch size, 
this extension will try to make the last frame the same as the first frame.
```

Ho ... `Batch size` ... or `Context batch size`  ? ... I tested both but nothing append ... it's alaws the same animation ... I have try on all  `Motion modules`.

The only thing that changes is that there is the number of images generated requested in `Context batch size` , for example if I set `Number of frames` to 6 and I set `Context batch size`  to 16 it will generate 16 images and the output animation on the Gif will be 6 frames. I am well aware that the opposite is required but it was just to point out that the `Context batch size` works well!

• 2 ] **Stride / Overlap**

I tried everything, nothing worked

### Steps to reproduce the problem

• 1 ] **Closed Loop**

1. Enable AnimateDiff
2. Press ` Closed loop ` to Enable
3. Number of frames : 16
4. Context batch size : 6
5. Generate

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/131191891/eb5cbbcf-ddf2-406c-8b02-e2b5dafa6362)
![00106-1](https://github.com/continue-revolution/sd-webui-animatediff/assets/131191891/7da5d65b-2501-49d0-87ae-e94b37b51fac)

• 2 ] **Stride / Overlap**

Stride      : I have try 1 ... 1.5 ... 2 ... 10 ... nothing change .... always the same Gif out.
Overlap  : I have try -1 ... 1 ... 4 ... 10 ... nothing change .... always the same Gif out.

### What should have happened?

• 1 ] **Closed Loop**

I thought it had 10 frames (16-6) so I could go back to the first frame so it would loop. But we can see that the animation does not loop. And if I generated the same animation by deactivating ` Closed loop `, we would have the same one.

• 2 ] **Stride / Overlap**

I admit I don't know at all what it should do... that's why I wanted to test it.

### Commit where the problem happens

webui: 1.6.0
extension: AnimateDiff 1.7.0

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --ckpt-dir 'S:\Model_1.5' --no-half-vae --api --medvram-sdxl
```

### Console logs

```
2023-09-29 14:04:55,207 - AnimateDiff - INFO - AnimateDiff process start.
2023-09-29 14:04:55,208 - AnimateDiff - INFO - You are using mm_sd_v15_v2.safetensors, which has been tested and supported.
2023-09-29 14:04:55,209 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.safetensors from D:\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.safetensors
2023-09-29 14:04:57,727 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-09-29 14:04:58,492 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.safetensors into SD1.5 UNet middle block.
2023-09-29 14:04:58,493 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.safetensors into SD1.5 UNet input blocks.
2023-09-29 14:04:58,493 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.safetensors into SD1.5 UNet output blocks.
2023-09-29 14:04:58,494 - AnimateDiff - INFO - Setting DDIM alpha.
2023-09-29 14:04:58,497 - AnimateDiff - INFO - Injection finished.
2023-09-29 14:04:58,497 - AnimateDiff - INFO - Hacking lora to support motion lora
2023-09-29 14:04:58,497 - AnimateDiff - INFO - Hacking ControlNet.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:42<00:00,  2.11s/it]
2023-09-29 14:05:44,744 - AnimateDiff - INFO - Restoring ControlNet.███████████████████| 20/20 [00:39<00:00,  2.10s/it]
2023-09-29 14:05:44,744 - AnimateDiff - INFO - Restoring hacked lora
2023-09-29 14:05:44,744 - AnimateDiff - INFO - Restoring DDIM alpha.
2023-09-29 14:05:44,744 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2023-09-29 14:05:44,744 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-09-29 14:05:44,746 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet middle block.
2023-09-29 14:05:44,746 - AnimateDiff - INFO - Removal finished.
2023-09-29 14:05:44,746 - AnimateDiff - INFO - Merging images into GIF.
2023-09-29 14:05:46,217 - AnimateDiff - INFO - AnimateDiff process end.
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:45<00:00,  2.26s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:45<00:00,  2.10s/it]
```

### Additional information

This never worked, I wanted to tell you after you changed FILM and imported Movie. But maybe I'm doing it wrong and I need to review the explanation...

However, I read the passage of the third point correctly of `How to use`

```
Enable Pad prompt/negative prompt to be same length and Batch cond/uncond and click Apply settings in Settings. 
You must do this to prevent generating two separate unrelated GIFs.
```

It's so cool to generate now over 75 tokkens. !! Thx a lot !

**Comment by continue-revolution** [comment]
Read readme before using it. I was having trouble supporting infinite v2v, but I do not want to remove UI.

**Comment by zopi4k** [comment]
I think it's you who didn't read me, I stipulated several times that I followed the read me to the letter and that nothing happened, and then I never talked about v2v.. . but from txt2Gif

**Comment by continue-revolution** [comment]
Not really, even for t2v you should not use them. These attributes are for both v2v and t2v. If infinite v2v is not supported, infinite t2v is unfortunately also not supported. Their logics are the same.

**Comment by zopi4k** [comment]
humm ... you mean "Closed loop" / "Stride" / "Overlap" are used only if I put a video in video source and this one are "infinite video"? 

Excuse me but the Read me it's really not clear ... as I had stipulated we don't know if you are talking about
“Context batch size” or “Batch size” of the webui ... ok you have a mega big mention of "infinite v2v" on ... I think I need exemple to understand it ^.^' sorry

**Comment by continue-revolution** [comment]
Short answer is - please do not use these three features at this time. When sometime those bold “do not use” disappear in readme, you should be able to use them. They should disappear no later than the end of  next week.

Edit “context batch size” to change video frame number for v1.6.0. Do not use “number of frames”.

**Comment by zopi4k** [comment]
O.O hooo ok ! it's not work actualy but you need for testing ^.^) 
Thx to reply me and sorry for distrub you ... the Read me just confused me. 

Afterwards I don't know if everyone will have understood, but I think I would have understood better like that :

 ``` [!!!Infinite V2V feature, DO NOT CHANGE, KEEP IT -1!!!] ```

change to ->  ``` [This feature is Work in Progress - please don't use it yet] ```

**Comment by rkfg** [comment]
To answer the OP: set the batch size to 16 and number of frames to 24 or more, then those features work. Looks like you need at least two batches to make a loop.

**Comment by continue-revolution** [comment]
@rkfg That’s right. I copied code from CLI where they wrote in that way.Even if it’s 17 frames it will have effect.

**Comment by GuruVirus** [comment]
Can you please update the readme to reflect that these are static and disabled? I was looking at the code like, wait, how is this parameter being passed if it is hardcoded... Took me a bit to realize it is always set to closed loop.

**Comment by continue-revolution** [comment]
@GuruVirus It works when your video frame number > context batch size, otherwise it won't work. In next version I will refactor README, and include this in README.
