### ISSUE TITLE
[Feature]: add optional setting to save images into custom folder

### ISSUE THREAD

**Issue by xyzDist** [continue-revolution/sd-webui-animatediff#161]
### Expected behavior

Hi, it is a minor feature request but I think is really useful, as keep current it's no option to save the images to other path, it mix with the original images folder which is really hard to organize, would love to have an option to save images to another folder instead of the default images folders, thanks!!

**Comment by continue-revolution** [comment]
yes, this is also something I want to do. actually, @zappityzap previously implemented this, but I did not take it because I did not realize the importance at that time.

I will bring it back in the next (or the next after the next) update.

**Comment by zappityzap** [comment]
I found it useful to have all the images from each batch in their own subfolder. There can be a lot of images per generation with interpolation.

**Comment by continue-revolution** [comment]
@zappityzap can you PR to bring it back?

**Comment by zappityzap** [comment]
I'll work on it.

**Comment by mweldon** [comment]
I wish it always saved at least 1 image, even if you uncheck the save box. Otherwise there is no way to recover the prompt.

**Comment by zappityzap** [comment]
TXT will save the prompt. The format isn't quite right but it's something for now. Saving infotext should be possible in all the output formats, with all the AD parameters too.
