### ISSUE TITLE
[Feature]: JSON Prompt Series

### ISSUE THREAD

**Issue by christopherquenneville** [continue-revolution/sd-webui-animatediff#169]
### Expected behavior

Hello!

First of all, thank you, amazing work.

I was wondering if you were planning on integrating support for JSON Prompt Series like you can do in https://github.com/s9roll7/animatediff-cli-prompt-travel or in Deforum.

This type of prompt:

    "prompt_fixed_ratio": 1.0,
    "head_prompt": "1girl, wizard, circlet, earrings, jewelry, purple hair,",
    "prompt_map": {
        "0": "",
        "8": "((fire magic spell, fire background))",
        "16": "((ice magic spell, ice background))",
        "24": "((thunder magic spell, thunder background))",
        "32": "((skull magic spell, skull background))",
        "40": "((wind magic spell, wind background))",
        "48": "((stone magic spell, stone background))",
        "56": "((holy magic spell, holy background))",
        "64": "((star magic spell, star background))",
        "72": "((plant magic spell, plant background))",
        "80": "((meteor magic spell, meteor background))"
    }

Thanks again,
Good day

**Comment by continue-revolution** [comment]
#164

**Comment by continue-revolution** [comment]
expect to wait for at least 2 days before it is available because I have an assignment due very soon.

**Comment by christopherquenneville** [comment]
Alright dude, you rock! Don't worry and take your time to complete your assignment.

**Comment by continue-revolution** [comment]
done via #164
