### ISSUE TITLE
[Feature]: animation off body can't move.

### ISSUE THREAD

**Issue by Mistermango23** [continue-revolution/sd-webui-animatediff#17]
### Expected behavior

Hello and this animation looks good but something was missing!  The body can't move properly, I once tried to make animation out of it, but the body in this picture animation doesn't want to moving and that would be nice if you could fix something, then the bodies can move freely.  Thanks

**Comment by continue-revolution** [comment]
I need your webui screenshot+your output. I will try the original repo. If the original repo is unable to achieve your feature request then it is also not possible in my extension.

**Comment by Mistermango23** [comment]
I'll do that after work with animation, it takes about 8 or 7 hours at work for me and then I'll do it.

**Comment by gitmylo** [comment]
> I'll do that after work with animation, it takes about 8 or 7 hours at work for me and then I'll do it.

I'll see if i can reproduce, i also noticed a lack of animation, while [animatediff's examples](https://animatediff.github.io/) look very animated, while the examples in this project's readme look very static.

# Reproductions
<details>
<summary>Using this extension</summary>

## Notice the lack of movement, it's just inconsistent jitter.


https://github.com/continue-revolution/sd-webui-animatediff/assets/36931363/c86a0c78-7c49-47b1-927c-b44c5c09f386


</details>

<details>
<summary>Using the original repo</summary>

## Notice the consistent movements, this one is actually animated.


https://github.com/continue-revolution/sd-webui-animatediff/assets/36931363/0a72c355-ceee-4079-85d6-731519856431


</details>

**Comment by gitmylo** [comment]
# Theory
It might be an issue with samplers, note that for the extension example i used `euler a`, but for the original repo i used `euler`.
I've seen issues in the past using the ancestral samplers. Especially in relation to video generations, i'll check if that could be it.

**Comment by Misterkiwi500** [comment]
ah! Now I know, now I get it, Because it's because a set it to FPS, look! that's the way if you do on less fps then it's very slow for animation but if you do on more fps then you can do much better on animations.

here is a proof from animation example:

8 FPS:
![df14f4db-02e8-4a13-a062-ca82b8018f5a](https://github.com/continue-revolution/sd-webui-animatediff/assets/53793601/c4725c81-3664-4ebe-95b2-a807b1e8c0c2)

32 FPS:
![01d0ef05-98cb-4c4b-b30d-debc89dbf82c](https://github.com/continue-revolution/sd-webui-animatediff/assets/53793601/86358185-978e-4160-ac09-c1256d4dddba)

128 FPS:
![95018262-537b-49f1-b309-adab32c7745b](https://github.com/continue-revolution/sd-webui-animatediff/assets/53793601/45e53ab3-2f3f-4109-80c5-d940e0345a0a)

256 FPS:
![14e76947-324a-400c-9f94-77b9689a8e65](https://github.com/continue-revolution/sd-webui-animatediff/assets/53793601/880a5fd4-6098-4197-bb86-865950830d91)

**Comment by Misterkiwi500** [comment]
I'm sorry but thank you! :)

**Comment by gitmylo** [comment]
> ah! Now I know, now I get it, Because it's because a set it to FPS, look! that's the way if you do on less fps then it's very slow for animation but if you do on more fps then you can do much better on animations.

Definitely not, those animations have the exact same issues. The fps just changes the amount of changing frames, there's absolutely no motion applied.

In other words, the animateDiff model is not being applied, the only thing it does here is improve temporal coherence, but there's no motion or anything.

**Comment by Misterkiwi500** [comment]
ok.... and what did i do wrong?

**Comment by gitmylo** [comment]
> ok.... and what did i do wrong?

There's an issue in this extension, which needs to be fixed before movements will look natural. It's not an issue from your end.

**Comment by Misterkiwi500** [comment]
well, I would have been very happy about the animation, so if they didn't move anything.. then it would also be sad.

**Comment by Misterkiwi500** [comment]
don't be surprised, i have two accounts on github. xD

**Comment by gitmylo** [comment]
> well, I would have been very happy about the animation, so if they didn't move anything.. then it would also be sad.

Try the official repo for now: https://github.com/guoyww/AnimateDiff/
I didn't get the official repo's webui working, but the scripts from config seem to work fine. That's how I generated the animated clip.

**Comment by continue-revolution** [comment]
Again, wait for 2 days or so and I will figure out wtf is wrong.

**Comment by zhanghongyong123456** [comment]
> Again, wait for 2 days or so and I will figure out wtf is wrong. The debug process is much harder for this one, compared to the SAM extension. The code for random generation is completely different between A1111 and diffusers+animatediff and the model architecture also differ subtlety

Yes, I also found that the animation generated by SD webui just flickers on the basis of the original image, without any movement，

**Comment by continue-revolution** [comment]
Hello everyone, I am still working hard to reproduce their samples, please wait patient as I am working on that. I will post here about my progress. Also, after I am able to reproduce somehow I will post a tutorial on how to reproduce their result on webui. Stay tuned.

**Comment by continue-revolution** [comment]
Due to some unknown reason, the output of the first resnet (even before entering motion module) in webui differ quite a bit from that in diffusers. I will have to investigate the reason

**Comment by Mistermango23** [comment]
Unfortunately, I don't know why.  I set how to do that on animatediff animation and this script worked but for the reason, sorry!  unfortunately I don't know.

**Comment by Mistermango23** [comment]
Unfortunately you have to find out.

**Comment by Mistermango23** [comment]
Maybe I have a solution to fix.  I got the message how to set it up correctly, look. 
https://github.com/guoyww/AnimateDiff/issues/75

**Comment by continue-revolution** [comment]
@Mistermango23 yes, 1.5 ckpt also don’t move on my side, even with the original repo. However, my responsibility is only to reproduce at least one of their result, and this is very hard and time-consuming because I have to investigate outputs later by layer. For people coming here later please be patient.

**Comment by continue-revolution** [comment]
The reason might be due to GroupNorm.

**Comment by continue-revolution** [comment]
Why is it hard to reproduce exactly the same output as the original repo?

My answer to this question is that: A1111 (or, ldm) has enormous amount of precision difference from diffusers. After diffusing the first step, they produce very similar result, but differ subtlely. As the diffusion step goes furthur (the similar, but subtlely different input to the same model), this difference will be enlargen and enlargen, resulting in the performance degradation you see on your panel. This brings an enormous amount of work on my side to reproduce the result in the original repo to A1111.

I give an example of output from the first diffusion step. This is the tensor value at the end.
A1111: [ 2.1121e+00, -6.0957e-01, -4.6791e-01,  ...,  2.1064e+00,
            2.6629e-01, -1.2186e-01]
AnimateDiff: [ 2.1104e+00, -6.0193e-01, -4.6279e-01,  ...,  2.1063e+00,
             2.7077e-01, -1.1119e-01]

After the 25th diffusion step, they become something like this:
A1111: [ 1.5121e+00, -7.4763e-01, -7.0178e-01,  ...,  1.4527e+00,
           -1.6306e-01, -2.8245e-01]
AnimateDiff: [-3.2058e-01, -5.9360e-01, -2.0773e-01,  ...,  6.8188e-01,
            -2.1290e-01,  9.8866e-01]

And the outputs look like this:
| A1111 | AnimateDiff |
| --- | --- |
| ![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/63914308/99116bfb-7bb8-485b-83c0-cad781761a5b) | 
![sample](https://github.com/continue-revolution/sd-webui-animatediff/assets/63914308/5105afe8-d497-4ab1-b5c4-37540e9601f8) |

This is indeed very awful. They start to differ from the very first resnet, even before entering the motion module.

**Comment by Misterkiwi500** [comment]
@continue-revolution and how long does it take to finish?

**Comment by Misterkiwi500** [comment]
I honestly wanted to say it's really sad when don't do animation. you know...

**Comment by continue-revolution** [comment]
@Misterkiwi500 You should know that as the developer, I am more frustrated seeing that my code doing shit because of something not written by me. I honestly have no idea how to fix that by now. Please wait patiently. I will have to investigate the weight and output of each layer in SD UNet.

**Comment by Misterkiwi500** [comment]
![s-l1600](https://github.com/continue-revolution/sd-webui-animatediff/assets/53793601/be7d6612-e0f6-4b9b-a68a-6dde746c4752)

**Comment by continue-revolution** [comment]
To clarify, this extension can do animation (at least in some settings), however, the performance is not as good as diffusers. Unlike ControlNet which is trained under ldm, this motion module is trained under diffusers, which inevitably brings some inconsistency.

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/issues/19#issuecomment-1648206197
