### ISSUE TITLE
[Bug]: 1b0759c2 returns incorrect number of images if interpolation is activated

### ISSUE THREAD

**Issue by kft334** [continue-revolution/sd-webui-animatediff#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

When using the API it is now pointless to use FILM interpolation since video_length images are returned even when interpolation is turned on. Please add an option to return a base64 encoded GIF or MP4 like it was before or return all 160 images or whatever the number is if video_length = 16 and interp_x = 10.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

The correct number of images should have been returned when interp = "FILM".

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
n/a
```

### Console logs

```Shell
n/a
```

**Comment by zappityzap** [comment]
The code to return video is still there in the code of animatediff_output.py if you want to uncomment it.

An option to choose what to return from the API call is probably a better long term solution.

**Comment by zappityzap** [comment]
Thanks for the bug report. I submitted a PR that will return all frames when interpolation is enabled.
