### ISSUE TITLE
[Feature]: Supported animated webp?

### ISSUE THREAD

**Issue by ekmett** [continue-revolution/sd-webui-animatediff#175]
### Expected behavior

Animated .webp images would render in browser unlike the current mp4 export that isn't even quicktime-compatible, and would allow you to retain the full color profile of the original sequence, given they are 24 bit color with a 8 bit alpha channel, and should be just directly supported in PIL. This would give the best of both worlds.

**Comment by continue-revolution** [comment]
I will merge #92 in a week, which supports webp. However, since this contributor change way more than I want to change, please give me more time before it is available.
