### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'restore'

### ISSUE THREAD

**Issue by daweiyi123** [continue-revolution/sd-webui-animatediff#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

*** Error running postprocess: F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py", line 69, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'

### Steps to reproduce the problem

Install the sd-webui-animatediff extension in the webui
Restart webui
Turn on AnimateDiff
Generate 1st try

### What should have happened?

im expecting the slow generation and generated gif

### Commit where the problem happens

extension: sd-webui-animatediff

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --no-half-vae --medvram-sdxl

call webui.bat
```

### Console logs

```Shell
*** Error running postprocess: F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py", line 69, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'
```

**Comment by continue-revolution** [comment]
your webui most likely do not have before_process. please update to v1.6.0

**Comment by daweiyi123** [comment]
im 1.6

**Comment by continue-revolution** [comment]
then restart

**Comment by daweiyi123** [comment]
Report the same mistake

**Comment by continue-revolution** [comment]
send me the full terminal log, including those INFO

**Comment by daweiyi123** [comment]
2023-10-07 16:18:36,653 - AnimateDiff - INFO - AnimateDiff process start.
2023-10-07 16:18:36,654 - AnimateDiff - WARNING - Your model mm_sd_v15_v2.ckpt has not been tested and supported. Either your download is incomplete or your model has not been tested. Please use at your own risk.
2023-10-07 16:18:36,654 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
*** Error running before_process: F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py", line 47, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 76, in inject
        self._load(model_name)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 48, in _load
        missed_keys = self.mm.load_state_dict(mm_state_dict)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
        raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
    RuntimeError: Error(s) in loading state_dict for MotionWrapper:
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    	Unexpected key(s) in state_dict: "mid_block.motion_modules.0.temporal_transformer.norm.weight", "mid_block.motion_modules.0.temporal_transformer.norm.bias", "mid_block.motion_modules.0.temporal_transformer.proj_in.weight", "mid_block.motion_modules.0.temporal_transformer.proj_in.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.to_q.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.to_k.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.to_v.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.to_out.0.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.to_out.0.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.to_q.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.to_k.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.to_v.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.to_out.0.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.to_out.0.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.norms.0.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.norms.0.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.norms.1.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.norms.1.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.ff.net.0.proj.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.ff.net.0.proj.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.ff.net.2.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.ff.net.2.bias", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.ff_norm.weight", "mid_block.motion_modules.0.temporal_transformer.transformer_blocks.0.ff_norm.bias", "mid_block.motion_modules.0.temporal_transformer.proj_out.weight", "mid_block.motion_modules.0.temporal_transformer.proj_out.bias". 
    	size mismatch for down_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for down_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for down_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for down_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for down_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for down_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for down_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for down_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for down_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for down_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.0.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.0.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.0.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.0.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.1.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.1.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.1.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.1.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 1280]) from checkpoint, the shape in current model is torch.Size([1, 24, 1280]).
    	size mismatch for up_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for up_blocks.2.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for up_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for up_blocks.2.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for up_blocks.2.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for up_blocks.2.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 640]) from checkpoint, the shape in current model is torch.Size([1, 24, 640]).
    	size mismatch for up_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for up_blocks.3.motion_modules.0.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for up_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for up_blocks.3.motion_modules.1.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.0.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).
    	size mismatch for up_blocks.3.motion_modules.2.temporal_transformer.transformer_blocks.0.attention_blocks.1.pos_encoder.pe: copying a param with shape torch.Size([1, 32, 320]) from checkpoint, the shape in current model is torch.Size([1, 24, 320]).

---
*** Error running postprocess: F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py", line 69, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---

**Comment by continue-revolution** [comment]
you have probably disabled hash calculation. please open it

**Comment by daweiyi123** [comment]
open hash calculation：

Calculating sha256 for F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors: 735e4c3a447a3255760d7f86845f09f937809baa529c17370d83e4c3758f3c75
2023-10-07 17:16:45,844 - AnimateDiff - INFO - AnimateDiff process start.
Calculating sha256 for F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt: 69ed0f5fef82b110aca51bcab73b21104242bc65d6ab4b8b2a2a94d31cad1bf0
2023-10-07 17:16:49,498 - AnimateDiff - INFO - You are using mm_sd_v15_v2.ckpt, which has been tested and supported.
2023-10-07 17:16:49,498 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
2023-10-07 17:16:53,430 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-10-07 17:16:54,178 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
*** Error running before_process: F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py", line 47, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 94, in inject
        unet.middle_block.insert(-1, self.mm.mid_block.motion_modules[0])
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\python\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'TimestepEmbedSequential' object has no attribute 'insert'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\extensions\sd-webui-animatediff\scripts\animatediff.py", line 69, in postprocess
        self.cn_hacker.restore()
    AttributeError: 'NoneType' object has no attribute 'restore'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by continue-revolution** [comment]
what's your pytorch version?

**Comment by daweiyi123** [comment]
F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\python>pip -V
pip 23.2.1 from F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\python\lib\site-packages\pip (python 3.10)

F:\SD\sd-webui-aki-v4.2\sd-webui-aki-v4.2\python>python -V
Python 3.10.11

**Comment by continue-revolution** [comment]
Open webui, scroll down to the bottom, copy and paste all version info here

**Comment by daweiyi123** [comment]
版本: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.11  •  torch: 1.12.1+cu113  •  xformers: 0.0.14.dev  •  gradio: 3.41.2  •

**Comment by continue-revolution** [comment]
pls update your pytorch via adding --reinstall-torch and --reinstall-xformers to your command line arguments

**Comment by germyparker** [comment]
I had the same problem as OP and --reinstall-torch and --reinstall-xformers solved it for me.

**Comment by leoSTM** [comment]
> pls update your pytorch via adding --reinstall-torch and --reinstall-xformers to your command line arguments

Not really working for me, still the same issue

**Comment by champkris** [comment]
Still not working for me after --reinstall-torch and --reinstall-xformers  argument

**Comment by zhangjinyangnwpu** [comment]
> pls update your pytorch via adding --reinstall-torch and --reinstall-xformers to your command line arguments

thanks, I solved this problem by upgrading to the latest version of torch and xformers
