### ISSUE TITLE
[Bug]: After use ADetailer,it will report RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [1280] and input of shape [32, 2560, 8, 8]

### ISSUE THREAD

**Issue by TinJieWang** [continue-revolution/sd-webui-animatediff#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

After use ADetailer,it will report RuntimeError:
  0%|                                                                                                      | 0/20 [00:00<?, ?it/s]
    RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [1280] and input of shape [32, 2560, 8, 8]

### Steps to reproduce the problem

1. Go to txt2img
2. select checkpoint of realisticVisionV51_v51VAE.safetensors [15012c538f]
3. With prompt: a girl,hair fluttering in the wind
4. Sampling method is DDIM
5. motion module is mm_sd_v15_v2.ckpt
6. number of frames :16 with fps 8
7. press generate

### What should have happened?

gif normally gererated

### Commit where the problem happens

webui:
extension:
AnimatedDiff

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
None
```

### Console logs

```Shell
RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [1280] and input of shape [32, 2560, 8, 8]
```

### Additional information

This is same to [issue78](https://github.com/continue-revolution/sd-webui-animatediff/issues/78). I can confirm that it's not an issue of a downloaded incomplete model.
The first time I used the Adetailer and animatediff features, everything was fine. However, when I clicked to generate again, this error occurred.

**Comment by continue-revolution** [comment]
Do not use adetailer with this extension
