### ISSUE TITLE
[Bug]: IT GOT STUCK

### ISSUE THREAD

**Issue by Someonetoldme584** [continue-revolution/sd-webui-animatediff#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

[Bug]: IT GOT STUCK 
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/79592731/776d1d75-9744-4cf6-a262-82a7ab6ef768)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

it should have worked

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
medvram xformers
```

### Console logs

```Shell
too slow and stuck
```

**Comment by WainWong** [comment]
You should check your graphics card and memory usage to make sure you're not exceeding the maximum amount of video memory
