### ISSUE TITLE
[Feature]: suggestion, multi controlnet source support

### ISSUE THREAD

**Issue by YoungkyuAlexKim** [continue-revolution/sd-webui-animatediff#188]
### Expected behavior

Is it possible to add a function to enter multiple control net sources in the current state?

Currently, it is possible to automatically extract controlnet sources from one video source to create animations, but some sources do not seem to be perfect to reflect the intention of the operator in the preprocessing phase.
(Especially for open pose, some joints can't be created at all, so it's often hard to fully trust.)

If an artist can source a separate animation path that is self-produced and extracted by other external programs such as blender or Maya, I think we can create a much more consistent and reflective outcome of the worker's intentions.

For your information, I am attaching an example of the animation pass that I made myself as a GIF.

If it's already a feature implemented in the current version and I didn't know about it, please don't pay much attention.

![depth](https://github.com/continue-revolution/sd-webui-animatediff/assets/12699623/d5e7f087-3c95-4cf4-b81e-bba4f60e3444)
depth
![seg](https://github.com/continue-revolution/sd-webui-animatediff/assets/12699623/ad3ec374-9f29-45b0-8af5-e11180749fbb)
seg
![walking](https://github.com/continue-revolution/sd-webui-animatediff/assets/12699623/9c0e4c46-d042-4ea9-bb95-1f2330b1a242)
openpose

all sources are created from other 3d program.

**Comment by continue-revolution** [comment]
It’s already supported in v1.7.0
