### ISSUE TITLE
Prompt Travel is not being triggered.

### ISSUE THREAD

**Issue by GoregoriDes** [continue-revolution/sd-webui-animatediff#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

As simple as the title says, there are no changes on any of the frames that I'm trying to change, and I'm not quite sure if this is a bug from the extension or is that I need to have something else enabled (probably another extension?)

### Steps to reproduce the problem

Adding the prompt, even the same stated in the example: 
1girl, origen, line, comet, wink, Masterpiece, BestQuality. UltraDetailed,
0: closed mouth
8: open mouth
smile

Then activating the extension. It only generates a smooth image (no open mouth or smile)

### What should have happened?

Change the image according to the prompt in the desired frame.

### Commit where the problem happens

webui: A1111
extension: https://github.com/continue-revolution/sd-webui-animatediff

### Command Line Arguments

```Shell
None.
```

### Console logs

```Shell
No errors.
```

**Comment by continue-revolution** [comment]
#193 #176

**Comment by zopi4k** [comment]
hummm ... do you use/try on 
"mm_sd_v15_v2" 

https://github.com/continue-revolution/sd-webui-animatediff/assets/131191891/f122ab17-32cc-4161-bba5-a98647cab298

or "mm-Stabilized_mid" ?

https://github.com/continue-revolution/sd-webui-animatediff/assets/131191891/e86cc02a-da78-4c77-8f88-d34b1dfd704e

and what checkpoint you use ?
