### ISSUE TITLE
[Feature]: OpenPose Control

### ISSUE THREAD

**Issue by p0mad** [continue-revolution/sd-webui-animatediff#20]
### Expected behavior

is it possible to use this alongside Controlnet Pose for generating specific pose for characters in videos?

**Comment by xdomiall** [comment]
Yes

**Comment by p0mad** [comment]
@xdomiall 
Thanks for the reply
Can you elaborate How to do it?

**Comment by continue-revolution** [comment]
this should have been supported via supporting ControlNet.
