### ISSUE TITLE
[Bug]: Install failed, No module named 'modules.sd_samplers_cfg_denoiser'

### ISSUE THREAD

**Issue by ryansteel0525** [continue-revolution/sd-webui-animatediff#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Install failed, No module named 'modules.sd_samplers_cfg_denoiser'
![1](https://github.com/continue-revolution/sd-webui-animatediff/assets/147627034/f439952d-d4a4-4bf8-bcee-a45c493ea0ef)
![2](https://github.com/continue-revolution/sd-webui-animatediff/assets/147627034/6a7a19a9-aa15-412e-ae94-b472d7085876)
![3](https://github.com/continue-revolution/sd-webui-animatediff/assets/147627034/f45ea110-8ab8-423c-89b3-9790387d769e)

### Steps to reproduce the problem

1. Go to .... 1
2. Press ....
3. ...
23

### What should have happened?

123

### Commit where the problem happens

webui: 1
extension: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
123
```

### Additional information

d

**Comment by continue-revolution** [comment]
Search before ask

**Comment by ryansteel0525** [comment]
Understood, but my webui was deployed on Aliyun cloud. So what shall I do ?

**Comment by continue-revolution** [comment]
Can’t you update your webui via git pull？
