### ISSUE TITLE
Doesn't create GIF and Video, SD Webui SageMaker Studio Lab ? 

### ISSUE THREAD

**Issue by Momcoc** [continue-revolution/sd-webui-animatediff#206]
When i use Animate Diff, i just get a grid of images and a bunch of separate images, what am i doing wrong?

**Comment by continue-revolution** [comment]
Copy and paste your terminal log here. If you don’t do this I cannot help you in any way

**Comment by Momcoc** [comment]
oh thanks, now I've solved the problem. I installed the Animatediff model via the Civitai Browser, the problem has been solved
