### ISSUE TITLE
 RuntimeError: CUDA error: invalid configuration argument

### ISSUE THREAD

**Issue by qwe666qq** [continue-revolution/sd-webui-animatediff#212]
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/129947810/761b72b8-399e-4c98-9a22-b0e0c11f431c)

**Comment by fish-lxh** [comment]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='jwd93tmuj6a_1440' coro=<Queue.process_events() done, defined at D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\queueing.py:384> exception=ValueError('[<gradio.queueing.Event object at 0x000002264A79C430>] is not in list')>
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.1\sd-webui-aki-v4.1\python\lib\site-packages\gradio\queueing.py", line 471, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queueing.Event object at 0x000002264A79C430>] is not in list

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff#attention
