### ISSUE TITLE
[Feature]: API Return ONLY .mp4 file

### ISSUE THREAD

**Issue by vicitooo** [continue-revolution/sd-webui-animatediff#218]
### Expected behavior

I would like to change the API call to send back only the generated .mp4 file. Currently, it sends all the frames and the information in them which sometimes is hundreds of MBs. Where should I start off? Which files should I be looking at? The automatic1111, the animatediff extension folder, or controlnet extension folder? 

Thanks in advance.

**Comment by continue-revolution** [comment]
There is no such option for api at this time because webui cannot return an mp4 file via api. If you can code, you should add additional layer to combine frames into an mp4 file outside A1111.

**Comment by continue-revolution** [comment]
You can also patch this extension and webui in any way you want. Everything about output is in https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_output.py
Whenever you meet a problem in A1111, just comment it. Do this in several rounds, when errors are cleared, you are fine.

**Comment by VictorValtchev** [comment]
I'm trying to do the same thing. Is animatediff_output really the part that returns the images from an API call? Which function is it?

**Comment by continue-revolution** [comment]
now api can return a video

**Comment by vicitooo** [comment]
I can't seem to find the endpoint in the server.py in ComfyUI? Maybe it's somewhere else?

**Comment by continue-revolution** [comment]
I can't help with anything related to ComfyUI. If you are using A1111, it should be possible now as long as you specify output format. GIF should almost absolutely work, but I don't know if base64 can encode mp4.
