### ISSUE TITLE
[Feature]: Additional parameters in txt file output

### ISSUE THREAD

**Issue by GuruVirus** [continue-revolution/sd-webui-animatediff#222]
### Expected behavior

The newer parameters are not included in the txt file output:

- Context batch size (also the readme says "Batch Size" but should be renamed to "Context batch size" to prevent confusion with SD's Batch Size parameter, in the line "Batch size — How many frames will be passed into the motion module at once").
- Stride
- Overlay
- Interp X (if FILM set to off, display "Off")
- Add Reverse Frame (On/Off)
- Remove Head (On/Off)
- Remove Tail (On/Off)

**Comment by continue-revolution** [comment]
#220 is doing this, but it's incomlete. It will be merged in a day.
