### ISSUE TITLE
[Bug]: 保存为MP4 格式时预览区无法显示

### ISSUE THREAD

**Issue by Myoko** [continue-revolution/sd-webui-animatediff#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

发现一个问题！文生图下保存动画格式选MP4 格式的时候 最后生成的动画在预览窗口无法显示！实际上顺利成功了MP4文件，也没有任何报错，MP4文件也在\txt2img-images\AnimateDiff文件夹里面  但GIF 格式就可以正常显示！
不知道有没有人有和我一样的问题？

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

每次生成MP4 就这样！GIF 就正常
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/3013386/bc8bd45b-fbca-478d-9498-8bc851b0e83f)

### Commit where the problem happens

webui: 1.6.0
extension: animatediff 1.9.1

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
Launching Web UI with arguments: --medvram --theme dark --xformers --no-half-vae --autolaunch
```

### Console logs

```Shell
没有错误
```

### Additional information

No response

**Comment by continue-revolution** [comment]
这只可能是gradio的问题

**Comment by gu-fan** [comment]
same here

**Comment by lilyzlt** [comment]
same here,  gradio: 3.41.2  which version of gradio you prefer?@continue-revolution
