### ISSUE TITLE
[Feature]: support X/Y/Z plot

### ISSUE THREAD

**Issue by xyzDist** [continue-revolution/sd-webui-animatediff#236]
### Expected behavior

Hi Dev,
is that possible to support X/Y/Z plot to test the parameters in both t2i and i2i?
thanks in advance!

**Comment by continue-revolution** [comment]
How do you actually want xyz plot given that output is a video?

**Comment by xyzDist** [comment]
it does works with regular parameters, like denoise. it will wedge out different videos properly, however the extension's parameters are not avalible in the dropdown list (like controlnet or adetailer). so I was wondering if it is possible. Thanks!
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/126343149/7303bd63-256f-4a84-a26e-c5e76cc4f02f)

**Comment by xyzDist** [comment]
the purpose is to test out setting different setting value. here is testing the denoise value for example.
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/126343149/b15a1e7c-b907-4ed4-979c-8c964086759f)

![00085-12345](https://github.com/continue-revolution/sd-webui-animatediff/assets/126343149/b45864d0-9a95-42bd-9070-72806414d664)
![00087-12345](https://github.com/continue-revolution/sd-webui-animatediff/assets/126343149/73aed561-520e-47de-beaf-b8babb570938)
![00088-12345](https://github.com/continue-revolution/sd-webui-animatediff/assets/126343149/b4aa538f-7945-4106-9168-5e5b0e1439f4)

**Comment by continue-revolution** [comment]
I understand. What kind of arguments in AnimateDiff do you want to test there?

**Comment by xyzDist** [comment]
Awesome!, Thanks a lot @continue-revolution.
Here are the argument ranking list to me.

- latent power
- latent scale
- optional latent power of last frame
- optional latent scale for last frame
- interp X
- context batch size
- stride
- overlap
- motion module

**Comment by continue-revolution** [comment]
Then please wait patiently since there is a long update list at #224 and I'm feeling overwhelmed

**Comment by xyzDist** [comment]
take your time, thanks for the efforts.

**Comment by solitaryTian** [comment]
> the purpose is to test out different setting value in a much easiest way. here is testing the denoise value for example. ![image](https://private-user-images.githubusercontent.com/126343149/277089006-b15a1e7c-b907-4ed4-979c-8c964086759f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg5MDA2LWIxNWExZTdjLWI5MDctNGVkNC05NzljLThjOTY0MDg2NzU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDMyNzJiMmZkNmE3YjZmOGU1MzBlMzA2ZDFiYjcwYWQ3NGYyOTYwMGIxMjA5MjI3MTc2MGU5ZTE2MTA3ODg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uxqUK1qiaExCWGTn9LT5x43dIsI34I8pbDTnPc3ZKAk)
> 
> ![00085-12345](https://private-user-images.githubusercontent.com/126343149/277088960-b45864d0-9a95-42bd-9070-72806414d664.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTYwLWI0NTg2NGQwLTlhOTUtNDJiZC05MDcwLTcyODA2NDE0ZDY2NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGFmMmQ0NDAwMzMxZmVmNzk0NDcwYzE0OTIzODFmMTMwYmQwMzljMDdiYWVlZDY4YzdlNTBhMWY0YTdkYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L2LT-tpTw3ADw0DuoMeY1DFTuNh5mrhEPom1t2u1Jds) [ ![00085-12345](https://private-user-images.githubusercontent.com/126343149/277088960-b45864d0-9a95-42bd-9070-72806414d664.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTYwLWI0NTg2NGQwLTlhOTUtNDJiZC05MDcwLTcyODA2NDE0ZDY2NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGFmMmQ0NDAwMzMxZmVmNzk0NDcwYzE0OTIzODFmMTMwYmQwMzljMDdiYWVlZDY4YzdlNTBhMWY0YTdkYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L2LT-tpTw3ADw0DuoMeY1DFTuNh5mrhEPom1t2u1Jds) ](https://private-user-images.githubusercontent.com/126343149/277088960-b45864d0-9a95-42bd-9070-72806414d664.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTYwLWI0NTg2NGQwLTlhOTUtNDJiZC05MDcwLTcyODA2NDE0ZDY2NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGFmMmQ0NDAwMzMxZmVmNzk0NDcwYzE0OTIzODFmMTMwYmQwMzljMDdiYWVlZDY4YzdlNTBhMWY0YTdkYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L2LT-tpTw3ADw0DuoMeY1DFTuNh5mrhEPom1t2u1Jds) [ ](https://private-user-images.githubusercontent.com/126343149/277088960-b45864d0-9a95-42bd-9070-72806414d664.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTYwLWI0NTg2NGQwLTlhOTUtNDJiZC05MDcwLTcyODA2NDE0ZDY2NC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGFmMmQ0NDAwMzMxZmVmNzk0NDcwYzE0OTIzODFmMTMwYmQwMzljMDdiYWVlZDY4YzdlNTBhMWY0YTdkYzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L2LT-tpTw3ADw0DuoMeY1DFTuNh5mrhEPom1t2u1Jds) ![00087-12345](https://private-user-images.githubusercontent.com/126343149/277088965-73aed561-520e-47de-beaf-b8babb570938.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY1LTczYWVkNTYxLTUyMGUtNDdkZS1iZWFmLWI4YmFiYjU3MDkzOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjIwMzFhNDc3N2ZlNmM2ZDE2YmI3NjgwNzZhOTk2ZDJjYmVmNmU4ZTU4MTZmNzY2OGYxNmFlYTExNDUzZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHr9-1KU25MTbJgrKXOYvswAqsYTzeNPydber2uS7AI) [ ![00087-12345](https://private-user-images.githubusercontent.com/126343149/277088965-73aed561-520e-47de-beaf-b8babb570938.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY1LTczYWVkNTYxLTUyMGUtNDdkZS1iZWFmLWI4YmFiYjU3MDkzOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjIwMzFhNDc3N2ZlNmM2ZDE2YmI3NjgwNzZhOTk2ZDJjYmVmNmU4ZTU4MTZmNzY2OGYxNmFlYTExNDUzZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHr9-1KU25MTbJgrKXOYvswAqsYTzeNPydber2uS7AI) ](https://private-user-images.githubusercontent.com/126343149/277088965-73aed561-520e-47de-beaf-b8babb570938.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY1LTczYWVkNTYxLTUyMGUtNDdkZS1iZWFmLWI4YmFiYjU3MDkzOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjIwMzFhNDc3N2ZlNmM2ZDE2YmI3NjgwNzZhOTk2ZDJjYmVmNmU4ZTU4MTZmNzY2OGYxNmFlYTExNDUzZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHr9-1KU25MTbJgrKXOYvswAqsYTzeNPydber2uS7AI) [ ](https://private-user-images.githubusercontent.com/126343149/277088965-73aed561-520e-47de-beaf-b8babb570938.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY1LTczYWVkNTYxLTUyMGUtNDdkZS1iZWFmLWI4YmFiYjU3MDkzOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjIwMzFhNDc3N2ZlNmM2ZDE2YmI3NjgwNzZhOTk2ZDJjYmVmNmU4ZTU4MTZmNzY2OGYxNmFlYTExNDUzZTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vHr9-1KU25MTbJgrKXOYvswAqsYTzeNPydber2uS7AI) ![00088-12345](https://private-user-images.githubusercontent.com/126343149/277088967-b4aa538f-7945-4106-9168-5e5b0e1439f4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY3LWI0YWE1MzhmLTc5NDUtNDEwNi05MTY4LTVlNWIwZTE0MzlmNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI5YmQyYTkxYTQxODBkOTdmM2Y0ZDIxZmRhM2I3ZGZkNTZkOWFlZGI2Mzk3NTNlYWIyODgwMzVmZmE1ODRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8bmRx_-tZFnj0bL7Opp4NDXE3CsTrQ8x8wYMS2wR-8) [ ![00088-12345](https://private-user-images.githubusercontent.com/126343149/277088967-b4aa538f-7945-4106-9168-5e5b0e1439f4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY3LWI0YWE1MzhmLTc5NDUtNDEwNi05MTY4LTVlNWIwZTE0MzlmNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI5YmQyYTkxYTQxODBkOTdmM2Y0ZDIxZmRhM2I3ZGZkNTZkOWFlZGI2Mzk3NTNlYWIyODgwMzVmZmE1ODRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8bmRx_-tZFnj0bL7Opp4NDXE3CsTrQ8x8wYMS2wR-8) ](https://private-user-images.githubusercontent.com/126343149/277088967-b4aa538f-7945-4106-9168-5e5b0e1439f4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY3LWI0YWE1MzhmLTc5NDUtNDEwNi05MTY4LTVlNWIwZTE0MzlmNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI5YmQyYTkxYTQxODBkOTdmM2Y0ZDIxZmRhM2I3ZGZkNTZkOWFlZGI2Mzk3NTNlYWIyODgwMzVmZmE1ODRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8bmRx_-tZFnj0bL7Opp4NDXE3CsTrQ8x8wYMS2wR-8) [ ](https://private-user-images.githubusercontent.com/126343149/277088967-b4aa538f-7945-4106-9168-5e5b0e1439f4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzIyMjAsIm5iZiI6MTcwMzQ3MTkyMCwicGF0aCI6Ii8xMjYzNDMxNDkvMjc3MDg4OTY3LWI0YWE1MzhmLTc5NDUtNDEwNi05MTY4LTVlNWIwZTE0MzlmNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQwMjM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI5YmQyYTkxYTQxODBkOTdmM2Y0ZDIxZmRhM2I3ZGZkNTZkOWFlZGI2Mzk3NTNlYWIyODgwMzVmZmE1ODRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8bmRx_-tZFnj0bL7Opp4NDXE3CsTrQ8x8wYMS2wR-8)

Hello, I want to test the video quality with different samplers using XYZ plot. But the results can not shows in a single picture or gif. So I want to ask you if your results with different  denoise value show in a single picture or gif? 
The following is my error information.



    Traceback (most recent call last):
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/modules/txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/modules/scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/scripts/xyz_grid.py", line 739, in run
        processed = draw_xyz_grid(
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/scripts/xyz_grid.py", line 365, in draw_xyz_grid
        grid = images.image_grid(processed_result.images[start_index:end_index], rows=len(ys))
      File "/dfs/comicai/guanyu.zhao/stable-diffusion-webui/modules/images.py", line 55, in image_grid
        w, h = imgs[0].size
    AttributeError: 'str' object has no attribute 'size'
