### ISSUE TITLE
[Feature]: Support more than 24 frames

### ISSUE THREAD

**Issue by Hellisotherpeople** [continue-revolution/sd-webui-animatediff#24]
### Expected behavior

Well, I modified the relevant parts of the UI code and the "max_len" arguments, but it appears that the actual model itself doesn't support more than 24 frames at a time. Is there any way to make this extension work for an (ideally unlimited) number of frames?

**Comment by continue-revolution** [comment]
cc @guoyww

**Comment by guoyww** [comment]
Hi @Hellisotherpeople , currently the recommended animation length is 16 frames since this is also the setting of our training data. We may support longer sequence generation in the future, thanks😊.

**Comment by Katehuuh** [comment]
Possible idea is to use last frame of the gif with low denoising strength as a initial images in img2img.
