### ISSUE TITLE
[Feature]:  support for OpenVINO/Intel arc

### ISSUE THREAD

**Issue by Wing13** [continue-revolution/sd-webui-animatediff#240]
### Expected behavior

Hello!
Will there be support for OpenVINO/Intel arc?
https://github.com/openvinotoolkit/stable-diffusion-webui/wiki/Installation-on-Intel-Silicon
Right now it is showing such an error:

`*** Error running postprocess: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 77, in postprocess
        self.prompt_scheduler.save_infotext_txt(res)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'`

**Comment by continue-revolution** [comment]
I don’t think this is Intel’s problem. You need to update your webui to 1.6.0

**Comment by Wing13** [comment]
My versions of everything:
webui: 1.6.0 python: 3.10.11 torch: 2.1.0.dev20230820+cpu xformers: N/A gradio: 3.41.2 checkpoint: deliberate_v3.safetensors [aadddd3d75]

**Comment by continue-revolution** [comment]
You may want to check if prompt_scheduler is really initiated. It is initialized at https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff.py#L51

I don’t think the error you showed has anything to do with OpenVINO

**Comment by Wing13** [comment]
The problem was with the openvino_accelerate.py script. Anyway, thank you for the great plugin!
https://github.com/openvinotoolkit/stable-diffusion-webui/issues/65
