### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by thezveroboy** [continue-revolution/sd-webui-animatediff#26]
### Expected behavior

thanks for the amazing extension!

works from the box on nvidia 3060, after the last update it quietly generates gifs 512x768

there are suspicions that there are memory leaks, since after a couple of generations the automatic1111 crashes with a lack of memory

**Comment by Lolologist** [comment]
I've seen the same.

**Comment by Golgovskiy** [comment]
Indeed, with every generation, memory is getting consumed until it crashes to torch.cuda.OutOfMemoryError. 0 bytes free, which is ridiculous. Obviously, extension never frees vram somewhere.

**Comment by ace2duce** [comment]
Same stil happening on the latest update

**Comment by QJieWang** [comment]
I have take much time on restarting webui since animatewebui, but I am still grateful to the author for sharing such a plugin.
 So When will this issue be fixed?

**Comment by continue-revolution** [comment]
Unfortunately, debugging memory leak is much harder than any other feature implementation and I’m busy. I will prioritize feature implementation. I cannot give a date on when I have time to figure it out.

**Comment by continue-revolution** [comment]
Also, as a developer, I restart webui hundreds of times per day. As a user, you enjoy much more.

**Comment by Golgovskiy** [comment]
@continue-revolution 

I understand the difficulty, as a developer myself. I am thankful for creating this extension.

 But as a user, on my home PC, I only have enough memory to run the generation 3 times. Less if I used batch. And every reloading takes several minutes too.  And then I need to reinput all of the settings again. 
Considering random result, I have given up using it, to be honest with you. I don't know how it is for everybody, but I think it would be great to first ensure your extension is usable, and then concentrate on features. It would help with your restarts too, you know.

Of course, the choice is yours still. I just think this is not a thing that should be delayed. Least all your new features will have to be rewritten to fix it later.

**Comment by continue-revolution** [comment]
1. I never run into OOM in my 4090 PC, unless I set width and height to be 1024*1024
2. I restart because of testing and bugs, not because of OOM
3. There seem to be ~0.2M memory leak, but I’m not sure where, I will have to investigate 
4. Debugging OOM may take several days but I don’t have that much time. If I don’t have the ability to figure it out in a short period of time (maybe several hours), feature update will take place before I have time

**Comment by continue-revolution** [comment]
A: 5.32 GB, R: 8.13 GB, Sys: 12.1/23.6445 GB (51.1%)
A: 5.32 GB, R: 8.13 GB, Sys: 12.4/23.6445 GB (52.2%)
A: 5.32 GB, R: 8.13 GB, Sys: 12.4/23.6445 GB (52.5%)
A: 5.32 GB, R: 8.13 GB, Sys: 12.1/23.6445 GB (51.2%)
A: 5.32 GB, R: 8.13 GB, Sys: 12.2/23.6445 GB (51.6%)
A: 5.32 GB, R: 8.14 GB, Sys: 12.1/23.6445 GB (51.2%)
A: 5.33 GB, R: 8.14 GB, Sys: 12.1/23.6445 GB (51.2%)

I honestly cannot observe obvious vram leakage in my own system setting. These 7 generations happen consecutively, without restarting WebUI, without moving to t2i generation then moving back to t2v... People here are welcome to post your own observation, especially how your vram usage change to fully saturated.
