### ISSUE TITLE
[Feature]: VRAM Optimizations

### ISSUE THREAD

**Issue by brandostrong** [continue-revolution/sd-webui-animatediff#262]
### Expected behavior

Are there any plans for more VRAM efficient processing? For example in batch/v2v with controlnets, how much VRAM is used is often a factor of how many images are in your batch, which is not the case for the webui's native batch implementation. For example, I easily exceed 24GB with over 300 images and two controlnets. Would it make a difference if the implementation was closer to native?

For example, all processing could be done only within the context batch size window(let's say 16), so instead of processing controlnets all at the beginning, and saving all of the images at the end, they would be done in batches of 16.  Doing it this way would have other benefits too. A more accurate ETA, and the ability to see in real time your output, instead of waiting >1hr to even see the first frame.

**Comment by continue-revolution** [comment]
#224 VRAM optimization is the next first priority

**Comment by continue-revolution** [comment]
done in v1.11.1
