### ISSUE TITLE
The api only return one image instead of a list of images

### ISSUE THREAD

**Issue by 1179021477** [continue-revolution/sd-webui-animatediff#264]
I use the post method to get the api results, but find that only one image is returned. I check the output "b64images = list(map(encode_pil_to_base64, processed.images)) if send_images else []". The length is 16. However i only get one base64 string in our post results.

**Comment by continue-revolution** [comment]
API issue will be fixed in the next update (approx. 3-4 days).

**Comment by 1179021477** [comment]
> API issue will be fixed in the next update (approx. 3-4 days).
thanks! please let me konw if API is ready

**Comment by 1179021477** [comment]
Hello, when will we can see the new updates?

**Comment by continue-revolution** [comment]
I'm busy with an extremely hard assignment which has already due and I'm using my late day. Wait patiently.

**Comment by continue-revolution** [comment]
done in v1.11.1
