### ISSUE TITLE
documentation request

### ISSUE THREAD

**Issue by extra-large-onions** [continue-revolution/sd-webui-animatediff#27]
( sorry if this is the wrong place to ask - I didn't see any discord/forum + not sure if i should ask here or the original AnimateDiff repo).
1. Is controlnet coming anytime soon
2. Will longer videos be supported
3. My videos always split into 2 separate animations: ![00028-100](https://github.com/continue-revolution/sd-webui-animatediff/assets/24745349/ff275d71-6baf-4f36-b1f1-ff3b1ad52581)
4. Gif with 0 movement when using img2img ( I did try mm 1.4 like some suggested, worked for txt2img but not for img2img)
5. Is there some prompting technique that's gonna create more movement than others

**Comment by Mozoloa** [comment]
same thing here on webui 1.6, img2img just create non moving image

**Comment by continue-revolution** [comment]
1, 2, 4, 5 supported, 3 fixed, see pined issue
