### ISSUE TITLE
[Bug]: Cannot use img2img batch with mask

### ISSUE THREAD

**Issue by kevmak** [continue-revolution/sd-webui-animatediff#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Refer to update log v1.10.0 have supported img2img batch and it seen also supported Inpaint batch mask. The extension can success work with batch without mask but failed with mask directory have been setup. 

### Steps to reproduce the problem

1. Go to img2img and select batch.
2. Fill in path with "Input directory", "Output directory", "Inpaint batch mask directory".
3. Ready generate image and mask generated by [Segment Anything](https://github.com/continue-revolution/sd-webui-segment-anything).
4. Provide video path/video source for AnimateDiff.
5. Press Generate to start.

### What should have happened?

Success the task and generate those image as video.

### Commit where the problem happens

webui: [1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.6.0)
extension: [37b7b58a]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### Console logs

```Shell
Traceback (most recent call last):
      File "D:\Projects\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Projects\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Projects\stable-diffusion-webui\modules\img2img.py", line 202, in img2img
        process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args, to_scale=selected_scale_tab == 1, scale_by=scale_by, use_png_info=img2img_batch_use_png_info, png_info_props=img2img_batch_png_info_props, png_info_dir=img2img_batch_png_info_dir)
      File "D:\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 283, in hacked_img2img_process_batch_hijack
        process_images(p)
      File "D:\Projects\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 119, in hacked_processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Projects\stable-diffusion-webui\modules\processing.py", line 803, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "D:\Projects\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_i2ibatch.py", line 168, in hacked_i2i_init
        self.mask = torch.asarray(1.0 - latmask).to(shared.device).type(self.sd_model.dtype)
                                  ^^^
    UnboundLocalError: cannot access local variable 'latmask' where it is not associated with a value
```

### Additional information

It seen been happen on [animatediff_i2ibatch.py#L159-L166](https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_i2ibatch.py#L159-L166) because when I debug program the `latmask` can't match any mask data.
I tried change L161 decision case from 
```python
elif self.latent_mask is not None:
```
to
```
else:
```
then it can work perfectly as wanted.

I don’t know if it is the program’s intended behavior.

**Comment by continue-revolution** [comment]
feel free to submit a PR and I will review accordingly, thanks.
