### ISSUE TITLE
[Bug]: Doesn't honor the Width (or perhaps width and height) of the picture. 

### ISSUE THREAD

**Issue by pipa0979** [continue-revolution/sd-webui-animatediff#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

When i am generating a picture with 512 x 512 vs 512 x 768. The picture looks massively different in the two different cases. Now when i enabled animate diff, with 512 x 768, it generates the gif with the picture(s) of 512 x 512. This should generate a gif that looks like  512 x 768 instead. It looks to be like when the animatediff is enabled, the resolution is switched back to 512 as a default which is a Bug. 

### Steps to reproduce the problem

1. Go to .... Stable diffusion and create a prompt and generate image with 512 x 512 (let's call it Image 1). Then recreate it with 512 x 768 (let's call it Image 2). Generate animated diff with 24 number of frames with 8 fps. 
2. The gif that gets generated with 512 x 768 follows how Image 1 looks like. It should look like Image 2. Note that Image 1 and 2 are massively different looking when you change the resolution of it. The bug is, animate diff i think is resetting the height (or the width or both to 512)

### What should have happened?

The bug is, animate diff i think is resetting the height (or the width or both to 512). There by the gif that gets created follows the resolution of 512x512 even though you explicitly it the resolution to 512 x 768 it doesn't get honored.

### Commit where the problem happens

webui: na
extension: na 

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --gradio-img2img-tool color-sketch

git pull
call webui.bat
```

### Console logs

```Shell
The bug is detailed in the previous steps.
```

### Additional information

na
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/10200606/ce6c7490-2b4f-4267-af6c-178bced0c7c6)

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/10200606/5ff81732-b4c2-4833-be00-645ca37b168b)

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/10200606/7178605c-466d-404c-95d2-fcaf3ae12e70)

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/10200606/0e9cab6d-c4d5-487c-8982-7b4d0f04dbee)

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/10200606/62861fc3-88fb-4c14-baee-35f9c37d849b)

**Comment by pipa0979** [comment]
As you can see, the 512 x 768 is not honored.

**Comment by continue-revolution** [comment]
I have never touched width and height. You should not use adetailer with this extension for the time being.
