### ISSUE TITLE
[Bug]: it generates noisy video

### ISSUE THREAD

**Issue by DavidDadd** [continue-revolution/sd-webui-animatediff#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

The animatediff generates noisy video.

### Steps to reproduce the problem

1girl,yoimiya (genshin impact),origen,line,comet,wink,Masterpiece,BestQuality. UltraDetailed,
0: closed mouth,
8: open mouth,
16: closed mouth,
smile,
Negative prompt: NSFW,logo,text,blurry,low quality,bad anatomy,sketches,lowres,bad proportions,cropped,watermark,signature,worstquality,grayscale,monochrome,normal quality,out of focus,username,
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 480306752, Size: 512x512, Model hash: fc2511737a, Model: chilloutmix_NiPrunedFp32Fix, AnimateDiff: "enable: True, model: mm_sd_v15_v2.safetensors, video_length: 17, fps: 8, loop_number: 0, closed_loop: A, batch_size: 16, stride: 1, overlap: 4, interp: Off, interp_x: 10, mm_hash: 1cf5d6d6", Version: v1.6.0-2-g4afaaf8a

### What should have happened?

it shouldn't be noisy video.

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --opt-sdp-no-mem-attention

call webui.bat
```

### Console logs

```Shell
.
```

### Additional information

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/95070694/3a7db719-eaa5-4cc2-97a7-d90e53471d4f)

[API](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)  •  [Github](https://github.com/AUTOMATIC1111/stable-diffusion-webui)  •  [Gradio](https://gradio.app/)  •  [Startup profile](http://127.0.0.1:7860/#)  •  [Reload UI](http://127.0.0.1:7860/)
version: [v1.6.0-2-g4afaaf8a](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [fc2511737a](https://google.com/search?q=fc2511737a54c5e80b89ab03e0ab4b98d051ab187f92860f3cd664dc9d08b271)

**Comment by continue-revolution** [comment]
This is normally a hardware issue. Restart webui can resolve your issue in most cases.
