### ISSUE TITLE
I get a noisy-blurry video

### ISSUE THREAD

**Issue by salvarob** [continue-revolution/sd-webui-animatediff#282]
I am following a tutorial from stable diffusion art https://stable-diffusion-art.com/animatediff/ but getting blurry videos. Any idea?

![00006-3210844823](https://github.com/continue-revolution/sd-webui-animatediff/assets/149901242/9ff59578-bd1a-4445-b42b-11ef5575a810)

**Comment by salvarob** [comment]
Ok, sorry for the question, I found the error myself... I WAS USING AN SDXL VAE WITH AN SD1.5-BASED MODEL

**Comment by continue-revolution** [comment]
If people meet similar issue, they can close AnimateDiff, generate a single image, and see if things go wrong.
