### ISSUE TITLE
[Bug]: Can not support prompt longer than 75 tokens

### ISSUE THREAD

**Issue by Z-YuPeng** [continue-revolution/sd-webui-animatediff#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I hope to write a long prompt that is more than 75 tokens, but I found it would generate a video containing two separate video slices. How could I solve it?

### Steps to reproduce the problem

Input a prompt of more than 75 tokens.

### What should have happened?

N/A

### Commit where the problem happens

WebUI: [v1.6.0-3-g45698ca2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/45698ca290a8531b465c1721ab423fad50cbba96)
extension: the latest cloned from GitHub

### Command Line Arguments

```Shell
NO
```

### Console logs

```Shell
N/A
```

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff#how-to-use 3
