### ISSUE TITLE
[Bug]: model file path does not update after moving webui folder

### ISSUE THREAD

**Issue by Hugs288** [continue-revolution/sd-webui-animatediff#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

i moved my webui folder but it is still looking for models in the old location

the animatediff tab is not appearing in txt2img or img2img.

### Steps to reproduce the problem

1. move webui folder
2. run webui

### What should have happened?

models should have been detected from extension folder/models

### Commit where the problem happens

webui: 1.6.0
extension: fd8a7f0be2e588e278ea7775aceb3a16e43aac68

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-no-mem-attention --no-half-vae --medvram-sdxl
```

### Console logs

```Shell
*** Error calling: J:\aistuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "J:\aistuff\stable-diffusion-webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "J:\aistuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 43, in ui
        return (AnimateDiffUiGroup().render(is_img2img, model_dir),)
      File "J:\aistuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 141, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\*username*\\Downloads\\aistuff\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

---
*** Error calling: J:\aistuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py/ui
    Traceback (most recent call last):
      File "J:\aistuff\stable-diffusion-webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "J:\aistuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 43, in ui
        return (AnimateDiffUiGroup().render(is_img2img, model_dir),)
      File "J:\aistuff\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_ui.py", line 141, in render
        os.mkdir(model_dir)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\*username*\\Downloads\\aistuff\\stable-diffusion-webui\\extensions\\sd-webui-animatediff\\model'

---
```

### Additional information

-

**Comment by continue-revolution** [comment]
Please edit for the time being. I'm aware of this problem but have no solution yet. It will be addressed in the next update.

**Comment by Hugs288** [comment]
> Please edit for the time being. I'm aware of this problem but have no solution yet. It will be addressed in the next update.

edit what?

**Comment by continue-revolution** [comment]
Settings/AnimateDiff, use a new path

or, delete attribute animatediff_model_path from config.json

**Comment by Hugs288** [comment]
alright, thank you
