### ISSUE TITLE
[Feature]: add object storage support for s3 protocol

### ISSUE THREAD

**Issue by zhangrc** [continue-revolution/sd-webui-animatediff#297]
### Expected behavior

The s3 protocol supports object storage such as amazon and minio to upload generated files.

The general way to achieve it is as follows:
First: add enable configuration, token, url configuration in webui
Second: After animatediff generates the file, read the configuration and submit the file to object storage

I can develop this feature, but it will take some time

**Comment by continue-revolution** [comment]
I'm not familiar with S3 protocol. Pls take your time to support that.
