### ISSUE TITLE
[Feature]: send keyframes to ControlNet, openpose or picture batch

### ISSUE THREAD

**Issue by gu-fan** [continue-revolution/sd-webui-animatediff#298]
### Expected behavior

instead of sending all frames, just use keyframes.
like prompt travel.

but one can use picture or openpose as the frame content.

but don't know whether it will be errorness or not, then generate with all batch is needed

**Comment by continue-revolution** [comment]
Yes, it is possible if you have per-frame rate. I expect to implement this feature in the next / next after the next update.

**Comment by continue-revolution** [comment]
It's already in my update plan, but I need to think more about how to implement it. Wait patiently.

**Comment by continue-revolution** [comment]
now this is implemented. simply add a new line in batch input dir in the following format:
keyframe:0,5,10,15
