### ISSUE TITLE
AnimateDiff on SDXL will soon be supported. DO NOT post feature request.

### ISSUE THREAD

**Issue by continue-revolution** [continue-revolution/sd-webui-animatediff#299]
### Expected behavior

^

**Comment by continue-revolution** [comment]
Done in 1.12.0

**Comment by F0xbite** [comment]
Very excited for this! However, it doesn't seem to be working for me. I only get 16 unrelated images. Using base SDXL model - sd_xl_base_1.0.safetensors [31e35c80fc]. 

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/133003026/fc022ee8-d09b-4cd1-b366-aff33fae0c84)

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/133003026/4f4255ab-a282-4046-a237-ed7a8986f4a9)

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/133003026/20cf1340-0ead-4084-b540-cca017a0e84b)
