### ISSUE TITLE
How come the VRAM usage of your repo much lesser than the offocial animatediff?

### ISSUE THREAD

**Issue by brappier** [continue-revolution/sd-webui-animatediff#304]
I am using official animate diff and the vram usage is very high ( even with xfomers) . what all changes did you do? 
Does your repo use fp16 whereas offical use fp32??

**Comment by continue-revolution** [comment]
1. yes, my repo use fp16 by default, which is actually A1111's setting
2. I don't know if the original repo implemented xformers properly. However, I've made sure that attention optimizations are implemented properly.
3. I don't guarantee if you will get the same result between A1111 and the official repo, but I can at least guarantee that both this repo and the official one can bring you reasonable gif if your prompt is good enough.

I will close this issue, but you can still ask questions and I will notice.
