### ISSUE TITLE
[Bug]: Shutterstock watermark everywhere since version 1.2.0, but absent in 1.1.0

### ISSUE THREAD

**Issue by Hellisotherpeople** [continue-revolution/sd-webui-animatediff#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Images generated with version 1.2.0 full of shutterstock watermarks, this literally never happened with version 1.1.0

### Steps to reproduce the problem

Update to version 1.2.0
do literally anything

### What should have happened?

Be like version 1.1.0 but with fixed bugs 

### Commit where the problem happens

webui: Latest
extension: 1.2.0

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
unimportant
```

### Console logs

```Shell
unimportant
```

### Additional information

You claim you "fixed the injection" in the readme but if this is fixed than I want it broken again.

**Comment by continue-revolution** [comment]
https://github.com/guoyww/AnimateDiff/issues/4#issuecomment-1631105505

**Comment by Hellisotherpeople** [comment]
Why did you close this? version 1.1.0 is literally better in everyway. It doesn't matter if it's "bugged", I want the "bugged" version.

**Comment by Hellisotherpeople** [comment]
The collab notebook also doesn't have this problem...

**Comment by continue-revolution** [comment]
Please visit the link I sent you. This is the problem of the training data, which means that it is not something that I am able to resolve. v1.1.0 is not a correct implementation. I had inserted motion modules to wrong place due to a typo.

If you generate GIF using the original repo, you will also see watermarks for at least some samples because I see them too.

**Comment by AI-Casanova** [comment]
@Hellisotherpeople would you be able to generate an example with identical settings between both versions? 

@continue-revolution if the older version does operate better, and unless someone takes the time and resources to retrain the motion model on a non-watermarked dataset, the "proper" implementation is nearly unusable. 

We may however be able to figure out exactly why your previous method worked better, and purposefully attempt to capture only the motion from their trained model and not the static watermark.

**Comment by continue-revolution** [comment]
@AI-Casanova because I inserted motion modules into the incorrect place due to a typo (wrote a 2 where it should be a 3). Again, in v1.2.1 I will give you the option to choose whichever you like. If you like the previous one, it should be trivial to switch back on your webui.

**Comment by rbychn** [comment]
@Hellisotherpeople is there a new fork you're working on? Can to tell me the best commit to pull before the watermarks start to show up?

**Comment by Amd321** [comment]
SO basically this extension is useless because the creator refuses to remove the watermark. Most likely because they plan to monetize it. Got it.

**Comment by rbychn** [comment]
> SO basically this extension is useless because the creator refuses to remove the watermark. Most likely because they plan to monetize it. Got it.

this creator has nothing to do with it, the model creators trained on Shutterstock data hence the watermark

**Comment by continue-revolution** [comment]
Now that some motion modules do not create this water mark, also the official v2 motion module do not create this watermark as well. Will close this issue for now.
