### ISSUE TITLE
[Bug]: 模型选项中无法更新模型，

### ISSUE THREAD

**Issue by Rambolv** [continue-revolution/sd-webui-animatediff#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

添加新模型后，使用刷新按钮，无法看到新模型，删除插件后重新安装，情况依旧，会显示以前用过的模型；
webui 是1.6.1；
尝试在完全没装过这个插件的webui中安装，可以显示添加的模型。
模型选择是否有数量上限？
如何解决此问题

### Steps to reproduce the problem

1. 往extensions\sd-webui-animatediff\model中添加新模型
2. 点击动画模型，无法显示新模型，即便全新安装的插件extensions\sd-webui-animatediff\model 中没有模型，依旧显示为以前用过的旧模型，看不到新模型；使用刷新按钮也无效。
3. 只有找一个从未安装过d-webui-animatediff\的webui，才能正常添加 和看到模型

### What should have happened?

1. 往extensions\sd-webui-animatediff\model中添加新模型
2. 点击动画模型，刷新 按钮后可以显示新模型

### Commit where the problem happens

webui: 1.6.1
extension: 最新版本

### Command Line Arguments

```Shell
--theme dark --opt-sdp-no-mem-attention --api --autolaunch --disable-safe-unpickle
```

### Console logs

```Shell
没有错误提示
```

**Comment by continue-revolution** [comment]
我无法复现你的问题，我本地一切正常

**Comment by BOTTLEii** [comment]
可能是因为大模型有冲突，换一个大模型可能就可以加载出来了
