### ISSUE TITLE
[Bug]: Some questions about img2img batch API

### ISSUE THREAD

**Issue by scutzzj** [continue-revolution/sd-webui-animatediff#312]
### Expected behavior

作者您好！
我在做与这个[https://github.com/continue-revolution/sd-webui-animatediff/issues/229](url)类似的工作。我仿照SD的img2img api写了一个img2img batch api，其能正常配合ControlNet进行调用，即与Web-UI中的img2img batch功能一致。
并且在log中显示，img2img.process_batch能被AD的hacked_img2img_process_batch_hijack劫持。
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/1c70564b-ef4d-465f-bedf-f9601be96ea6)

于是我在api请求的payload中添加了您在[https://github.com/continue-revolution/sd-webui-animatediff#api](url)中说明的alwayson_scripts参数，但会出现关于ControlNet的如下报错：
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/9c2a0f4a-cac7-4c08-b9ac-d905d592f346)

我查看了一下，正常使用WebUI的batch功能时，animatediff_cn.py的hacked_processing_process_images_hijack函数中，units打印出来的内容如下：
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/c33489b4-3261-4cc3-97e5-e09dd10b4927)
而在我调用batch的api时，该变量则变为如下：
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/f1cb7eb7-b2dc-4d36-9b81-20db952d6bca)

另外，基于txt2img api的AD V2V方法，当我在ControlNet参数中，设置input_image为video path第一帧或者所有帧的liet时，得到的视频都是不动的（即您README中提及的整个视频都会以输入的控制图作为参考），而当我将input_image注释掉时（测试过在img2img api中注释掉该参数，即意味着WEB-UI中的沿用输入图片，与您在[https://github.com/continue-revolution/sd-webui-animatediff#controlnet-v2v](url)中第四点保持一致），则会出现如下报错：
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/7e801c9c-b398-457e-bd21-5464ef67e2b6)
此时的units变量打印出来也是<internal_controlnet.external_code.ControlNetUnit object at 0x7f6a206908e0>而非预期的<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7fb5343919c0>。

Q：
1、感觉ControlNet并没有被正确转移，是不是因为我在调用API模式的SD时，没有使用到AnimateDiffScript.ui函数对AD进行初始化，导致ControlNet依然是原始形态呢？

2、我该如何让ControlNet与AD统一？

3、关于AD的api，测试结果为，不添加ControlNet时，都能正常运行，结果也符合预期（能动或者不能动）。在添加ControlNet试图进行V2V后，txt2img和img2img batch都会报错，是我用得不对吗？
附上payload片段。
        "controlnet": {
                "args": [
                    {
                        "module": "dw_openpose_full",
                        "model": "control_v11p_sd15_openpose [cab727d4]",
                        "processor_res": 512, 
                        "guidance_start": 0,
                        "guidance_end": 1.0,
                    }
                ]
            },
            'AnimateDiff': {
                'args': [{
                    'model': 'mm_sd_v15_v2.safetensors',   # Motion module
                    'format': ['PNG', 'Frame'],      # Save format, 'GIF' | 'MP4' | 'PNG' | 'WEBP' | 'WEBM' | 'TXT' | 'Frame'
                    'enable': True,         # Enable AnimateDiff
                    'video_length': len(os.listdir(input_dir)),     # Number of frames
                    'fps': 15,               # FPS
                    'loop_number': 0,       # Display loop number
                    'closed_loop': 'R+P',   # Closed loop, 'N' | 'R-P' | 'R+P' | 'A'
                    'batch_size': 16,       # Context batch size
                    'stride': 1,            # Stride 
                    'overlap': -1,          # Overlap
                    'interp': 'Off',        # Frame interpolation, 'Off' | 'FILM'
                    'interp_x': 10,          # Interp X
                    'video_path': input_dir,       # Video path
                    'latent_power': 1,      # Latent power
                    'latent_scale': 32,     # Latent scale
                    'last_frame': None,     # Optional last frame
                    'latent_power_last': 1, # Optional latent power for last frame
                    'latent_scale_last': 32,# Optional latent scale for last frame
                    'request_id': ''        # Optional request id. If provided, outputs will have request id as filename suffix
                    }
                ]
            }

十分感谢。

**Comment by scutzzj** [comment]
排查了一下ControlNet，看上去是API模式下的SD调用的也是API模式的ControlNet，而ControlNet API模式并没有batch_images的属性。请问是否有什么方法，让我在SD的API模式下也能调用ControlNet的UI模式对象？
-----------------
# ControlNet UI模式下的属性
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/cd424155-4fe7-4693-a753-275c31d88e17)

# ControlNet API模式下的属性
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/21038147/38eb161b-f06e-425f-b946-78dd252cddab)

**Comment by continue-revolution** [comment]
CN没有给API支持batch_images参数。你可以给CN插件提PR

**Comment by scutzzj** [comment]
> CN没有给API支持batch_images参数。你可以给CN插件提PR

我自己实现了，稍微修改您的animatediff_cn.py文件即可，现在我可以使用API调用controlnet v2v功能。
十分感谢~

**Comment by moonsunstars39** [comment]
@scutzzj 
你好，请问要如何修改animatediff_cn.py使得video path输入在api模式下可以正常调用controlnet v2v呢？
十分感谢！

**Comment by scutzzj** [comment]
> @scutzzj 你好，请问要如何修改animatediff_cn.py使得video path输入在api模式下可以正常调用controlnet v2v呢？ 十分感谢！

把'batch_images'这个属性添加到unit变量里，还要写一个SD的img2img batch的API才能调用，比较麻烦

**Comment by moonsunstars39** [comment]
@scutzzj 非常感谢！
请教一下img2img batch的API您是怎么写呢？

**Comment by ValentiaSulli** [comment]
> > CN没有给API支持batch_images参数。你可以给CN插件提PR
> 
> 我自己实现了，稍微修改您的animatediff_cn.py文件即可，现在我可以使用API调用controlnet v2v功能。 十分感谢~

您好，这部分工作可以分享出来吗？感谢~
