### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'is_xl'

### ISSUE THREAD

**Issue by mikeyimer** [continue-revolution/sd-webui-animatediff#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

![捕获11111](https://github.com/continue-revolution/sd-webui-animatediff/assets/137673481/b291f28a-655c-4027-b83a-fae0d088450b)

The pictures have been generated in the txt2img-images folder, but the videos have not been generated.
webui version: v1.6.0 ,ControlNet v1.1.416

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

 AttributeError: 'NoneType' object has no attribute 'is_xl'

### Commit where the problem happens

webui: 
extension: 
sd-webui-animatediff

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--no-gradio-queue --theme=dark --xformers --no-half-vae --enable-insecure-extension-access
```

### Console logs

```Shell
*** Error running postprocess: E:\SDXL\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "E:\SDXL\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "E:\SDXL\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 86, in postprocess
        motion_module.restore(p.sd_model)
      File "E:\SDXL\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_mm.py", line 109, in restore
        inject_sdxl = sd_model.is_sdxl or self.mm.is_xl
    AttributeError: 'NoneType' object has no attribute 'is_xl'
```

**Comment by continue-revolution** [comment]
I don't believe that this could be constantly triggered. If your frames can be generated normally, the only possibility is that you clicked "Remove motion module from any memory" by accident.

**Comment by mikeyimer** [comment]
> I don't believe that this could be constantly triggered. If your frames can be generated normally, the only possibility is that you clicked "Remove motion module from any memory" by accident.

I did press "Remove motion module from any memory" by mistake
