### ISSUE TITLE
[Feature]:  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)

### ISSUE THREAD

**Issue by hechushitaoyuan** [continue-revolution/sd-webui-animatediff#317]
### Expected behavior

 RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper_CUDA___slow_conv2d_forward)

**Comment by continue-revolution** [comment]
Search before ask.
