### ISSUE TITLE
Low Quality output with AnimateDiff_XL

### ISSUE THREAD

**Issue by pellaaa93** [continue-revolution/sd-webui-animatediff#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I tried AnimateDiff_XL with JuggernautXL checkpoint. It can succesfully inject motion modules but output are extremely low quality and grainy (they looks ultra low res). I tried with png, mp4 and gif but get the same results... is that normal? I ran it on a 3090 (tried both xformers and sdp)

### Steps to reproduce the problem

Render a txt2img with 2m sde exponential sampler at 50steps with Animatediff enabled. (no loop, no source video)

### What should have happened?

better image quality like 1.5 animatediff

### Commit where the problem happens

webui: 1.6.0 (no dev)
extension: last

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--no-half-vae --autolaunch --disable-safe-unpickle
```

### Console logs

```Shell
no specific log
```

**Comment by continue-revolution** [comment]
Unfortunately, there is not too much that I can do. From my testing, XL model works well with their settings, but it’s not quite robust - when you change to your own settings, you need to spend a lot of time trying to cherry-pick a good one.

let’s wait for them to release a stable motion module.

**Comment by pellaaa93** [comment]
I used their resolution and everything, so do you suggest changing the sampler to euler? will try
