### ISSUE TITLE
[Feature]: Support for new SEINE (image 2 video) model

### ISSUE THREAD

**Issue by CCpt5** [continue-revolution/sd-webui-animatediff#336]
### Expected behavior

Curious if there'll be support implemented for the SEINE model that was released yesterday. I played w/ the repo locally this morning and it was capable. It did need V1.4 in diffusers format though.  

Re: https://github.com/Vchitect/SEINE 

https://github.com/continue-revolution/sd-webui-animatediff/assets/37972078/dc6e0ee8-7861-4486-85ab-a33a06982599

**Comment by continue-revolution** [comment]
I’m happy to support, but I may not have enough availability recently, so please wait patiently.
