### ISSUE TITLE
[Bug]: In SD.Next, AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl' when using SD1.5 models

### ISSUE THREAD

**Issue by LankyPoet** [continue-revolution/sd-webui-animatediff#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

When enabling AnimateDiff then running with SD1.5 models, I receive the following error in SD.Next and cannot proceed with an animation:
 AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl' 

### Steps to reproduce the problem

1. Start SD.NEXT, ensure on ORIGINAL backend
2. Select SD 1.5 model
3. Make a text prompt
4. Select the following options (though any combination I've tried doesn't change things):
Motion module
mm_sd_v15_v2.ckpt
Save format
GIF
MP4
PNG
TXT
Enable AnimateDiff
Number of frames16
FPS16
Display loop number0
Closed loopN
Context batch size16
Stride1
Overlap-1
Frame InterpolationFILM
Interp X4
5. Click Generate
6. Error occurs

### What should have happened?

No error and the extension should have proceeded. I believe the most recent version prior to this one worked OK.

### Commit where the problem happens

webui:
20:06:55-312418 INFO     Starting SD.Next
20:06:55-312418 INFO     Python 3.11.6 on Windows
20:06:55-405568 INFO     Version: app=sd.next updated=2023-11-21 hash=bee397e8
                         url=https://github.com/vladmandic/automatic/tree/master
20:06:55-705445 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.6
extension: 794875c

### Command Line Arguments

```Shell
C:\sdnext\webui.bat --upgrade
```

### Console logs

```Shell
20:20:50-389965 ERROR    Error running before process: extensions\sd-webui-animatediff\scripts\animatediff.py: AttributeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮│ C:\sdnext\modules\scripts.py:508 in before_process                                                                                ││                                                                                                                                   ││   507 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                                ││ ❱ 508 │   │   │   │   script.before_process(p, *script_args, **kwargs)                                                            ││   509 │   │   │   except Exception as e:                                                                                          ││                                                                                                                                   ││ C:\sdnext\extensions\sd-webui-animatediff\scripts\animatediff.py:51 in before_process                                             ││                                                                                                                                   ││    50 │   │   │   params.set_p(p)                                                                                                 ││ ❱  51 │   │   │   motion_module.inject(p.sd_model, params.model)                                                                  ││    52 │   │   │   self.prompt_scheduler = AnimateDiffPromptSchedule()                                                             ││                                                                                                                                   ││ C:\sdnext\extensions\sd-webui-animatediff\scripts\animatediff_mm.py:63 in inject                                                  ││                                                                                                                                   ││    62 │   │   self._load(model_name)                                                                                              ││ ❱  63 │   │   inject_sdxl = sd_model.is_sdxl or self.mm.is_xl                                                                     ││    64 │   │   sd_ver = "SDXL" if sd_model.is_sdxl else "SD1.5"                                                                    ││                                                                                                                                   ││ C:\sdnext\venv\Lib\site-packages\torch\nn\modules\module.py:1695 in __getattr__                                                   ││                                                                                                                                   ││   1694 │   │   │   │   return modules[name]                                                                                       ││ ❱ 1695 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                                   ││   1696                                                                                                                            │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'
```

**Comment by continue-revolution** [comment]
I am not able to accomodate any request about vlad fork, especially if
- you are using diffusers backend instead of official SAI backend
- vlad implements new line as BREAK
- any other feature that is in conflict with A1111
Please ask vlad for help.

Also, I don't think vlad has this problem previously. It must be because vlad pushed some breaking change internally.

**Comment by LankyPoet** [comment]
Thank you. For clarity, I was using original backend. I will also post this in SD.Next issues and reference this to keep both projects updated.

**Comment by LankyPoet** [comment]
Closing as this is fixed in dev of SD.Next. Thank you.
