### ISSUE TITLE
[Feature]: training scripts for motion modules

### ISSUE THREAD

**Issue by x-CK-x** [continue-revolution/sd-webui-animatediff#35]
### Expected behavior

is this a possibility to be added & what would be needed?

**Comment by continue-revolution** [comment]
I don't think they have officially released the training code. If they have released, I can try to see if it's possible to integrate it into the "Train" tab.

That said, I would assume that you have some coding experience/can properly use your terminal if you want to train your own motion module. I think it would be better to type on your terminal and train separately from A1111, just like [kohya scripts](https://github.com/kohya-ss/sd-scripts/).

**Comment by Katehuuh** [comment]
@continue-revolution https://github.com/tumurzakov/AnimateDiff/blob/main/Fine_tune_AnimateDiff.ipynb

**Comment by continue-revolution** [comment]
The official training script has been released. I do not plan to support training in this extension. It is always much better if you could use another software which is specifically designed for training, such as [kohya scripts](https://github.com/kohya-ss/sd-scripts/) and a bunch of community forks.
