### ISSUE TITLE
From the author: update paused until mid next week, after 12/9/2023

### ISSUE THREAD

**Issue by continue-revolution** [continue-revolution/sd-webui-animatediff#351]
I am aware of the recent advance of StableDiffusion based video generation, including open-sourced SVD from SAI, close-sourced Gen-2 from RunwayML, Pika V1 from PikaLab, etc; and a whole bunch of workflows in Comfy or something - I know that people are really excited and are eager to try these new toys.

However, since I am extraordinary busy with my university assignments (~~2~~1 compiler course assignments almost not started but due soon ~~, 2 final exams happening early next week~~), I will have to pause update until mid next week, when I'm done with all these shits. You may have noticed that there is no major update for more than a week. Unfortunately, people living in the internat sadly have to face the reality that prevent them from doing anything interesting.

My next plan is to support Stable Video Diffusion, if no one else attempt to support it in A1111 during this period. I believe that the next generation of AnimateDIff is also coming soon, which will also be put in the first priority.

`12/06/2023`: due to the fact that I'm feeling extraordinary overwhelmed, I will need to rest for a few more time.

`12/09/2023`: I do not want to work on the compiler assignment anymore, so the update will resume. This issue will be closed once I submit that compiler final project.

**Comment by Rodin10** [comment]
Thanks for your work on this, good luck with the university assignments!

**Comment by chlolch** [comment]
期待

**Comment by continue-revolution** [comment]
Finally submitted. Finally can close this.
