### ISSUE TITLE
[BUG]: 用ADetailer来修脸 抖有残影

### ISSUE THREAD

**Issue by OEIEE** [continue-revolution/sd-webui-animatediff#353]
### Expected behavior

导入已有视频来生成mp4,用ADetailer来修脸,脸会不停抖,有残影,有BUG或不兼容,如何修复?  
扩展都升级成最新版本了. 用SD-webui.

仅文字生成没问题.

**Comment by Rambolv** [comment]
...我从来没有这个问题...作者大概率不会主动适配ADETAILER

**Comment by joshua76y** [comment]
因为adtailer是经过animatediff处理后补画的脸，所以不受它控制，画出来就会每帧不一样，流程决定的，没办法

**Comment by continue-revolution** [comment]
we move any discussion about adetailer to https://github.com/continue-revolution/sd-webui-animatediff/issues/446#issuecomment-1999421486
