### ISSUE TITLE
[Bug]: ControlNet V2V inpaint error (T2I)

### ISSUE THREAD

**Issue by red-sponge** [continue-revolution/sd-webui-animatediff#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

When I run InPaint, I get an error and the video doesn't generate properly. (T2I)
![스크린샷 2023-12-02 200139](https://github.com/continue-revolution/sd-webui-animatediff/assets/127950543/24331e72-c478-40ff-808b-d34ffc78f3f0)

### Steps to reproduce the problem

1. Go to ControlNet Inpaint Unit
2. Enter a folder which contains two sub-folders image and mask in Input Directory of Batch tab
![스크린샷 2023-12-02 212445](https://github.com/continue-revolution/sd-webui-animatediff/assets/127950543/8cf20265-f77e-420a-b1c2-f610c7941a82)

3. Generate with enable Animatediff 
![스크린샷 2023-12-02 201636](https://github.com/continue-revolution/sd-webui-animatediff/assets/127950543/6f226fa2-0224-4d0b-b098-4b23889b3de0)

### What should have happened?

New footage is only generated for the masked area

### Commit where the problem happens

webui: version: [v1.6.0-2-g4afaaf8a]
extension: [d2e77f40]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --api
```

### Console logs

```Shell
*** Error running process: C:\SD\webui_160-2\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\SD\webui_160-2\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\SD\webui_160-2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 993, in process
        self.controlnet_hack(p)
      File "C:\SD\webui_160-2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 982, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\SD\webui_160-2\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 496, in hacked_main_entry        final_inpaint_mask = final_inpaint_feed[0, 3, :, :].astype(np.float32)
    IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
```

**Comment by xilai0715** [comment]
The same problem.
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/134478402/5a17be8e-8d96-4e21-92bc-89eb3a3c09c0)

**Comment by continue-revolution** [comment]
this problem has been fixed, the doc will be updated in a day
