### ISSUE TITLE
[Bug]: <minor aesthetic:>  typo in scripts/animatediff_lora.py  line 26 -    logger.info("Hacking loral to support motion lora")

### ISSUE THREAD

**Issue by rbfussell** [continue-revolution/sd-webui-animatediff#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

a typographical error in loader output

### Steps to reproduce the problem

1. attempt to generate image
2. read output

### What should have happened?

should have said 
  * Hacking lora to support motion lora 
or 
  * Hacking LoRa to support motion LoRa   -- if you want to be really pedantic

### Commit where the problem happens

webui: all
extension: current

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Brave, Apple Safari, Microsoft Edge

### Command Line Arguments

```Shell
--any
```

### Console logs

```Shell
really it's just a type,
```

### Additional information

it's not super important,  just a small typo,   It could say whatever it wants to really,  everything else works okay.  probably should have just fixed it and made a pull,   but I don't have access to a clean repo locally at the moment.;

**Comment by continue-revolution** [comment]
next time if you see a typo, please submit a PR directly and I will merge immediately. thanks

this time please also submit a pr because I'm too busy recently and don't have time to push a fix before Dec 7th

**Comment by rbfussell** [comment]
> thanks for your report.
> 
> next time if you see a typo, please submit a PR directly and I will merge immediately.
> 
> this time please also submit a pr because I'm too busy recently and don't have time to push a fix before Dec 7th
> 
> if you don't code, search some substring inside the codebase and replace with a fix.
> 
> if I don't see a pr by Dec 7th I'll fix it on my own.

I should have waited to to do that,  I just have not been home,  holidays,  etc.   just figured I'd forget if I didn't put it somewhere.

**Comment by rbfussell** [comment]
PR submitted:  Closing.
