### ISSUE TITLE
Rendering quailty problem

### ISSUE THREAD

**Issue by joshua76y** [continue-revolution/sd-webui-animatediff#359]
大佬能看懂中文我就用中文描述更清晰了：
我在webui中用animatediff通过controlnet控制生成序列帧（无论是文生图还是图生图批量处理），最终渲染出来的序列帧都跟我做单帧预览的差别比较大，缺少很多细节，象是step步数没跑完的感觉。
其中用的重绘幅度跟cfg值，种子，模型，lora，controlnet设置等各方面设置都是一样的，动画序列帧能顺利跑出来的。
请问这是什么原因导致的？有办法解决吗？
![00000-a_100](https://github.com/continue-revolution/sd-webui-animatediff/assets/42955367/4e20a8a1-4366-49a9-a380-f8da05798559)
![07558-4292945649-(closed_eyes_0 988),(eating_0 962),(blurry_0 955),(food_0 954),(blurry_background_0 91),(depth_of_field_0 841),(holding_food_0 7](https://github.com/continue-revolution/sd-webui-animatediff/assets/42955367/bccc0a96-643f-490e-a4c9-188a2e6732d8)

**Comment by continue-revolution** [comment]
恐怕没有。AnimateDiff会让画面复杂度下降几乎是普遍现象了，我觉得这么轻量，即插即用的模型，能达到这个效果已经不错了。
