### ISSUE TITLE
invitation from sd-webui-controlnet

### ISSUE THREAD

**Issue by lllyasviel** [continue-revolution/sd-webui-animatediff#360]
please let us know if you want to join repo `sd-webui-controlnet` with writing permission. You will be able to commit any codes if anything is conflicting with animatediff as long as new codes are tested and do not break t2i/i2i.

thanks!

**Comment by continue-revolution** [comment]
Thanks for your invitation. Yes, I would like to join immediately. My current code base has too much code duplicates
