### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HellKaiser45** [continue-revolution/sd-webui-animatediff#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Hello,

I'm having trouble getting a simple animation right. The results are not satisfactory. My basic workflow involves vid2vid with controlnet openpose on comfyui. First, I extract the poses from my video. Then, I use the Ksampler (I've tried several combinations of samplers and schedulers).

![myworkflow](https://github.com/continue-revolution/sd-webui-animatediff/assets/124168150/91974a32-3d5e-402e-bc6c-5074af705a3d)

I've also tried various checkpoints (even the recommended ones), but the results are quite odd. It's as if the image is overly "baked". For example:

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/124168150/656e8999-845e-4d5b-88c1-f8b9ef7207f5)

The quality of this image is far inferior to what the model is capable of at this resolution, as you can see here:

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/124168150/cff10f63-b2ca-4c27-ac1f-21c285f439cb)

I suspect the issue might be due to an incompatible Python library, possibly PyTorch. I can't pinpoint the exact problem.

Can anyone help me resolve this issue?

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

a good quality animation

### Commit where the problem happens

webui: comfyui
extension: impactpack

### Command Line Arguments

```Shell
default
```

### Console logs

```Shell
nothing interesting
```

**Comment by continue-revolution** [comment]
This repo is the extension for A1111 users, not for Comfy. Please post your issue to the Comfy node you use. That said, this extension can achieve most features you want, especially CN V2V. If you have any problem using my extension in A1111, you are welcome to post another issue to ask.

**Comment by HellKaiser45** [comment]
sorry for that I'll definitely try it with A1111.
