### ISSUE TITLE
[Bug]: Why can I only generate one set of images without generating an animation?

### ISSUE THREAD

**Issue by dongkuang** [continue-revolution/sd-webui-animatediff#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Why can I only generate one set of images without generating an animation?

### Steps to reproduce the problem

1. Go to webui,
2. input: (sfw:1.2),(best quality,masterpiece:1.2),1 girl,
              0:smile,in the school,long hair,
              25:eyes_closed,in the bedroom,
              purple hair,
3.output: one set of images
(sfw:1.2),(best quality,masterpiece:1.2),1 girl,
0:smile,in the school,long hair,
25:eyes_closed,in the bedroom,
purple hair,
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3143324565, Size: 512x512, Model hash: 8d0ce6c016, Model: sd_xl_refiner_1.0_0.9vae, VAE hash: 63aeecb90f, VAE: sdxl_vae.safetensors, Version: v1.6.0-2-g4afaaf8a
Time taken: 48.3 sec.
![stab](https://github.com/continue-revolution/sd-webui-animatediff/assets/14137651/e8c27d72-9e47-4503-b617-0ecf4ef248da)
Please help me!Thank you!

### What should have happened?

an animation

### Commit where the problem happens

webui:  one set of images
extension: sd-webui-animatediff

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
bash webui.sh --listen --api --xformers --allow-code
```

### Console logs

```Shell
*** Error running postprocess_batch_list: /home/tg/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/home/tg/stable-diffusion-webui/modules/scripts.py", line 667, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/home/tg/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 78, in postprocess_batch_list
        self.prompt_scheduler.save_infotext_img(p)
    AttributeError: 'NoneType' object has no attribute 'save_infotext_img'
```

### Additional information

(sfw:1.2),(best quality,masterpiece:1.2),1 girl,
0:smile,in the school,long hair,
25:eyes_closed,in the bedroom,
purple hair,
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3143324565, Size: 512x512, Model hash: 8d0ce6c016, Model: sd_xl_refiner_1.0_0.9vae, VAE hash: 63aeecb90f, VAE: sdxl_vae.safetensors, Version: v1.6.0-2-g4afaaf8a
Time taken: 48.3 sec.

**Comment by us-Mike** [comment]
me too

**Comment by sergiobr** [comment]
me too

**Comment by allen-chi** [comment]
Same here, started suddenly.

**Comment by Blindripper** [comment]
Somebody found a solution? Same here.

**Comment by continue-revolution** [comment]
For OP: You are using sd15 motion module for sdxl.

**Comment by Dowgen** [comment]
解决了吗兄弟

**Comment by us-Mike** [comment]
> 解决了吗兄弟

Number of frames是8的倍数，且>=32帧。

**Comment by dongkuang** [comment]
> For OP: You are using sd15 motion module for sdxl.

This is
