### ISSUE TITLE
[Feature]: FreeInit

### ISSUE THREAD

**Issue by edwinzeng2005** [continue-revolution/sd-webui-animatediff#367]
### Expected behavior

We need this feature to get more stable animations.
https://github.com/TianxingWu/FreeInit

**Comment by xpeng** [comment]
just see this too.

> In this repository, we use [AnimateDiff](https://animatediff.github.io/) as an example to demonstrate how to integrate FreeInit into current text-to-video inference pipelines.

**Comment by continue-revolution** [comment]
Someone I personally know of has implemented freeinit but he thinks that the result is not as good as they advertised. I may still ask him to pr anyway.

**Comment by continue-revolution** [comment]
freeinit will be merged in a day. I will close this issue for now
