### ISSUE TITLE
[Feature]: 请问如何设置才能在视频生成完成后，实时显示在网页上

### ISSUE THREAD

**Issue by CccccchenJD** [continue-revolution/sd-webui-animatediff#368]
### Expected behavior

当前生成完一个视频，似乎只能手动从保存路径下载。有什么办法能设置为实时在网页上浏览生成结果吗

**Comment by continue-revolution** [comment]
choose gif as your output format and you will see it displayed on your frontend. unfortunately due to gradio you cannot see anything if you only select "mp4" as your output format.
