### ISSUE TITLE
[Feature]: New Update! 👀

### ISSUE THREAD

**Issue by Mistermango23** [continue-revolution/sd-webui-animatediff#370]
### Expected behavior

Look at this! a new Version of animatediff V3 https://github.com/guoyww/AnimateDiff
@continue-revolution !!!!!!!

**Comment by continue-revolution** [comment]
Wait, wait, wait. I’ve been working full night for my compiler assignment for 2 days. If you want to see more update instead of my obituary, you will have to be more patient.

**Comment by dancemanUK** [comment]
> Wait, wait, wait. I’ve been working full night for my compiler assignment for 2 days. If you want to see more update instead of my obituary, you will have to be more patient.

谢谢你的努力，我们不急。

**Comment by continue-revolution** [comment]
After partial investigation of the update -
1. Supporting new motion module will very easy. change to the repo would be minimal
2. Supporting new adapter (lora) will be also very easy, but I need to investigate the difference between motion lora and domain adapter
3. Having a good user experience of ControlNet while having a not-too-bad implementation (meaning that the code duplicate would be minimal) is always very challenging, so do the new control models from AnimateDiff researchers

So here is the plan -
- In v1.13.0 which may come today or tomorrow, you will be able to use new motion module and new adapter. Code change will only happen in this repository.
- In v2.0.0 which may come sometime next week, you will be able to use new control models as well as magic animate through ControlNet panel. Code change will mainly happen in sd-webui-controlnet (I also have write permission there).

**Comment by armynew** [comment]
waiting for new version release,thank you !

**Comment by continue-revolution** [comment]
v1.13.0 has been released, which means that V3 motion module and V3 domain adapter have been supported. Make sure to read https://github.com/continue-revolution/sd-webui-animatediff?tab=readme-ov-file#v3.

This issue will be closed when v2.0.0 is released, which means that SparseCtrl and Magic Animate are supported.

**Comment by LIQUIDMIND111** [comment]
> v1.13.0 has been released, which means that V3 motion module and V3 domain adapter have been supported. Make sure to read https://github.com/continue-revolution/sd-webui-animatediff?tab=readme-ov-file#v3.
> 
> This issue will be closed when v2.0.0 is released, which means that SparseCtrl and Magic Animate are supported.

ok , so after reading, im confuse in this: v3 model goes to the MODEL animatediff folder, and v3 ADAPTER goes in the LORA folder? and needs to be ACTIVATED as a LORA?

**Comment by continue-revolution** [comment]
@LIQUIDMIND111 yes. Adapter is optional.

**Comment by LIQUIDMIND111** [comment]
> @LIQUIDMIND111 yes. Adapter is optional.

ok im testing it already and just seems that MOTION loras from v2 give error when you activate them using base v3. Is this normal since motion loras are for v2 only?

**Comment by continue-revolution** [comment]
V3 does not have mid block injection but V2 does. Motion Lora also applied to mid block motion modules, so they are not compatible.

**Comment by LIQUIDMIND111** [comment]
> V3 does not have mid block injection but V2 does. Motion Lora also applied to mid block motion modules, so they are not compatible.

got you... 👯

**Comment by LIQUIDMIND111** [comment]
> V3 does not have mid block injection but V2 does. Motion Lora also applied to mid block motion modules, so they are not compatible.

hey friend, one question, FOR COMFY UI, do we need to use other models for animate diff? or can we use the same we use for auto1111 like mm1.5_v2_safetensor?

**Comment by continue-revolution** [comment]
You can use motion module there, but I’m not sure how they implement adapter.

**Comment by LIQUIDMIND111** [comment]
> You can use motion module there, but I’m not sure how they implement adapter.

ok, i already tried, works ok, maybe auto111 works better.... v3 works well with LCM in auto1111 ... look.

https://github.com/continue-revolution/sd-webui-animatediff/assets/112510084/cd329550-3d88-439d-868e-1e7d21e6583e

**Comment by continue-revolution** [comment]
SparseCtrl is already available in dev branch and it's working properly. I will close this, though v2.0.0 will be released a few days later after I've done with magic animate and a bunch of side features.

**Comment by m20renderz** [comment]
> > You can use motion module there, but I’m not sure how they implement adapter.
> 
> ok, i already tried, works ok, maybe auto111 works better.... v3 works well with LCM in auto1111 ... look.
> 
>  00009-3336737030.mp4

LCM as in sampler or LORA? which v3 module is this , please share workflow, thanks
