### ISSUE TITLE
[Bug]: AttributeError: 'Options' object has no attribute 'get'. Did you mean: 'set'

### ISSUE THREAD

**Issue by FMsunyh** [continue-revolution/sd-webui-animatediff#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/9877644/fd6829d5-abfe-42bd-99b9-26c4121ebc59)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

。

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
。
```

### Console logs

```Shell
。
```

### Additional information

。

**Comment by continue-revolution** [comment]
You are at a currently not tested dev branch. Please do not do that and checkout master branch.
