### ISSUE TITLE
The MP4 quality generated after Pad prompth varies greatly. What is the possible reason?

### ISSUE THREAD

**Issue by randompaga** [continue-revolution/sd-webui-animatediff#376]
This is before pad:
![0](https://github.com/continue-revolution/sd-webui-animatediff/assets/46378941/b4d2f553-cdcf-4cd0-a49b-b1fafed3d09d)
This is after the pad:
![8](https://github.com/continue-revolution/sd-webui-animatediff/assets/46378941/cbb1e197-6c26-444b-853b-83f6382f8275)

The parameters before and after the pad are as follows. I have carefully checked them and they are exactly the same:

 {'prompt': '(masterpiece:1.2,top quality, best quality),1girl,best quality,masterpiece,realistic,close-up,simple background', 'negative_prompt': '(worst quality:2),(low quality:2),(normal quality:2),lowres,(worst quality, low quality:2),monochrome,zombie,overexposure,watermark,bad hand,extra hands,extra fingers,too many fingers,fused fingers,bad arm,distorted arm,extra arms,fused arms,extra legs,missing leg,disembodied leg,extra nipples,detached arm,liquid hand,inverted hand,disembodied limb,oversized head,extra body,extra navel,easynegative,(hair between eyes),duplicate,ugly,huge eyes,worst face,(bad and mutated hands:1.3),horror,geometry,bad_prompt,(bad hands),(missing fingers),multiple limbs,(interlocked fingers:1.2),Ugly Fingers,(extra digit and hands and fingers and legs and arms:1.4),(deformed fingers:1.2),(long fingers:1.2),(bad-artist-anime),bad-artist,bad hand,extra legs,(ng_deepnegative_v1_75t),grayscale,normal quality,lowres,sketches,low quality,NSFW,nsfw', 'styles': None, 'seed': -1, 'subseed': -1, 'subseed_strength': 0, 'seed_resize_from_h': -1, 'seed_resize_from_w': -1, 'sampler_name': 'DPM++ SDE Karras', 'batch_size': 1, 'n_iter': 1, 'steps': 20, 'cfg_scale': 7.0, 'width': 512, 'height': 768, 'restore_faces': False, 'tiling': None, 'do_not_save_samples': False, 'do_not_save_grid': False, 'eta': 0.67, 'denoising_strength': 0.5, 's_min_uncond': None, 's_churn': None, 's_tmax': None, 's_tmin': None, 's_noise': None, 'override_settings': None, 'override_settings_restore_afterwards': True, 'refiner_checkpoint': None, 'refiner_switch_at': None, 'disable_extra_networks': False, 'comments': None, 'enable_hr': True, 'firstphase_width': 0, 'firstphase_height': 0, 'hr_scale': 1.3, 'hr_upscaler': 'realesr-general-x4v3', 'hr_second_pass_steps': 3, 'hr_resize_x': 0, 'hr_resize_y': 0, 'hr_checkpoint_name': None, 'hr_sampler_name': None, 'hr_prompt': '', 'hr_negative_prompt': '', 'sampler_index': 'DPM++ SDE Karras', 'script_name': None, 'script_args': [], 'send_images': True, 'save_images': False, 'alwayson_scripts': {'AnimateDiff': {'args': [{'model': 'mm_sd_v14.ckpt', 'format': ['PNG'], 'enable': True, 'video_length': 16, 'fps': 6, 'loop_number': 0, 'closed_loop': 'R+P', 'batch_size': 16, 'stride': 1, 'overlap': -1, 'interp': 'Off', 'interp_x': 10, 'video_source': '', 'video_path': '/samples', 'latent_power': 1, 'latent_scale': 32, 'last_frame': None, 'latent_power_last': 1, 'latent_scale_last': 32, 'request_id': ''}]}}}

**Comment by continue-revolution** [comment]
Resolved in communication via bilibili private message.

If anyone meets similar issues - lock your seed and generate to see if there is any difference.
