### ISSUE TITLE
the use of ControlNet with masks is not working properly.[Bug]: 

### ISSUE THREAD

**Issue by ai-is-in-wonderland** [continue-revolution/sd-webui-animatediff#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

"For those who wish to inpaint videos: place the folders 'image' and 'mask' within the ControlNet inpainting unit's folder. Both sub-folders must contain an equal number of images. The system will automatically pair them in sequence."
Regarding this part, it seems that the use of ControlNet with masks is not working properly. Here is the error log:

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

working properly

### Commit where the problem happens

webui: ver1.7.0
extension: sd-webui-animatediff

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
*** Error running process: C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
File "C:\stablediffusion20230811\stable-diffusion-webui\modules\scripts.py", line 718, in process
script.process(p, *script_args)
File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
self.controlnet_hack(p)
File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
self.controlnet_main_entry(p)
File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 496, in hacked_main_entry
final_inpaint_mask = final_inpaint_feed[0, 3, :, :].astype(np.float32)
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
```

### Additional information

No

**Comment by continue-revolution** [comment]
I've not properly tested inpainting previously but now I am doing a V2 refactor and it's a good chance for a thorough test. Can you give me a part of your data, including images and masks, for testing purpose?

**Comment by ai-is-in-wonderland** [comment]
These are the images and masks I used for the test. 
And the video demonstrates the method I used.
![00001](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/6a19dbde-362b-4f92-9b8d-a7906841e6f6)
![00002](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/71ad1bd6-0722-45bf-a1b1-5fead79df8c0)
![00003](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/f1c7de1f-5a3c-41fa-bccb-b5d926a116af)
![00004](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/4855ddef-eba4-4ce9-8507-e368418065e2)
![00005](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/35de124c-a78e-4836-b4ef-ab83d7bc94b4)
![00006](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/1943c0c1-073c-4f80-8171-7567795aa4cc)
![00007](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/9c5266e4-89cc-4395-9655-ed87f168e669)
![00008](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/2e3fbb43-7f7f-4ce7-8007-81a55c6051e2)
![00009](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/39896804-59ac-49b0-aad3-19026427e753)
![00010](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/a9656a30-350b-49f4-9032-00a6f6fce44c)
![00011](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/2de7d570-461c-4094-8b2a-60d1a38cdf63)
![00012](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/32b41dbb-d53a-4f8e-ab86-6004cc20a34a)
![00013](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/dd03087f-c43a-4ad0-a36a-76e39b24ec6d)
![00014](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/583ba459-d9c0-4912-9a2a-5948d273b6e4)
![00015](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/6a5fcf7f-bdd2-4854-ba8c-d9cc705a679c)
![00016](https://github.com/continue-revolution/
![00001](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/3f5a22ee-2754-401c-b9cf-091cd3529888)
![00002](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/b41c9ca5-3492-4024-83cf-76cfabb170eb)
![00003](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/674774bc-46f9-44cc-9c59-7e5106737331)
![00004](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/b4fcb18e-8047-496a-80e1-200c893d5615)
![00005](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/f18387df-de85-4905-a997-88c2134db0d3)
![00006](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/6a359daf-3cad-49ef-a4bb-e9677b2a4c8f)
![00007](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/6f6e54d3-1685-471f-a3d9-5274e72c92e3)
![00008](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/94de0843-110f-41a8-abd2-d1f3f729c093)
![00009](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/4eadd471-74b7-4dbb-a3e7-c25cec13dc04)
![00010](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/24d36e1d-47aa-484d-b4c6-b9f66f7341cd)
![00011](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/6423c295-980b-4827-806b-d4072fda9d5b)
![00012](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/1bd95069-abd8-4ad2-b8dc-bb0b53a9f41d)
![00013](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/faa0e025-a901-4d86-95fb-592dce67af4b)
![00014](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/56483a17-5b8a-4304-b54c-a5a0bd9a13c5)
![00015](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/61d18221-2dda-48b3-b16d-e9d4789a6171)
![00016](https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/828c0dcf-1248-4ab4-8d0b-49ecc0583d9e)
sd-webui-animatediff/assets/133919481/f5c14744-b52e-4380-bf33-0a73e8e11de6)

https://github.com/continue-revolution/sd-webui-animatediff/assets/133919481/1d1ebe8f-6056-488c-afff-9912cc2ba821

**Comment by continue-revolution** [comment]
the issue with inpaint should have been fixed. docs will be updated in a day.
