### ISSUE TITLE
[Feature]: Save and load animatediff settings

### ISSUE THREAD

**Issue by otorre1** [continue-revolution/sd-webui-animatediff#384]
### Expected behavior

This feature should be very useful

**Comment by continue-revolution** [comment]
I also want this feature, but this feature has to do with some subtle features in Gradio, so it may take some time.

**Comment by zappityzap** [comment]
I added a branch to work on this called zz/paste-infotext. It's working but needs more testing, and I think the extra AD settings for img2img could be added.

**Comment by marcsyp** [comment]
Please note that if you use Config Presets, you can add the elem ids to the config and save ADiff configurations nicely.  I couldn't live with Config Presets. The list of ids for Config Presets is as following (scraped from the code):


#AnimateDiff t2i
img2img-ad-motion-module
img2img-ad-save-format
img2img-ad-enable
img2img-ad-video-length
img2img-ad-fps
img2img-ad-loop-number
img2img-ad-closed-loop
img2img-ad-batch-size
img2img-ad-stride
img2img-ad-overlap
img2img-ad-interp-choice
img2img-ad-interp-x
img2img-ad-video-path
#img2img-ad-latent-power
#img2img-ad-latent-scale
#img2img-ad-latent-power-last
#img2img-ad-latent-scale-last

#AnimateDiff i2i
img2img-ad-motion-module
img2img-ad-save-format
img2img-ad-enable
img2img-ad-video-length
img2img-ad-fps
img2img-ad-loop-number
img2img-ad-closed-loop
img2img-ad-batch-size
img2img-ad-stride
img2img-ad-overlap
img2img-ad-interp-choice
img2img-ad-interp-x
img2img-ad-video-path
#img2img-ad-latent-power
#img2img-ad-latent-scale
#img2img-ad-latent-power-last
#img2img-ad-latent-scale-last

**Comment by continue-revolution** [comment]
zappityzap should have done this update. If you need more, please tag him here.
