### ISSUE TITLE
用API生成的动画，每一帧是独立的，不连贯，看日志没问题

### ISSUE THREAD

**Issue by liuchunyu524** [continue-revolution/sd-webui-animatediff#392]
"override_settings": {
                "sd_model_checkpoint": "Realistic Vision V5.1(VAE)"
            },
            "alwayson_scripts": {
                "AnimateDiff": {
                    "args": [
                        {
                            "model": 'mm_sd_v15_v2.ckpt',   # Motion module
                            "format": ['MP4', 'PNG'],        # Save format, 'GIF' | 'MP4' | 'PNG' | 'WEBP' | 'WEBM' | 'TXT' | 'Frame'
                            "enable": True,         # Enable AnimateDiff
                            "video_length": 16,     # Number of frames
                            "fps": 8,               # FPS
                            "loop_number": 0,       # Display loop number
                            "closed_loop": 'R-P',   # Closed loop, 'N' | 'R-P' | 'R+P' | 'A'
                            "batch_size": 16,       # Context batch size
                            "stride": 1,            # Stride 
                            "overlap": -1,          # Overlap
                            "interp": 'Off',        # Frame interpolation, 'Off' | 'FILM'
                            "interp_x": 10,         # Interp X
                            "video_source": None,   # Video source
                            "video_path": '',     # Video path
                            "latent_power": 1,      # Latent power
                            "latent_scale": 32,     # Latent scale
                            "last_frame": None,     # Optional last frame
                            "latent_power_last": 1, # Optional latent power for last frame
                            "latent_scale_last": 32,# Optional latent scale for last frame
                            "request_id": ''        # Optional request id. If provided, outputs will have request id as filename suffix
                        }
                    ]
                }
            },

**Comment by continue-revolution** [comment]
post your full API call in another issue if you still face this issue after updating everything.
