### ISSUE TITLE
[Bug]: Generate throw index error all the sudden - no changes to settings and was working fine before

### ISSUE THREAD

**Issue by LordHellscream** [continue-revolution/sd-webui-animatediff#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

It was working fine for long time with many different prompt/models,

but all the sudden today it gives this error :

index 24 is out of bounds for dimension 0 with size 24

doesn't matter if i change to number of frames to anything 16 or even 1 still throw this error.

The error logs indicate failing somewhere at

single_cond 

method of the

AnimateDiffPromptSchedule 

class, where it is trying to interpolate between two prompt conditions using slerp.

Full log:

https://pastebin.com/dkUBhErV

updated the latest

### Steps to reproduce the problem

It just suddenly happened, rebooting, restarting Automatic1111 don't resolve it.
Any model , number of frame, or prompt (no matter how simple) triggers this.

### What should have happened?

it should start generate

### Commit where the problem happens

webui: automatic1111
extension:  animatediff

### Command Line Arguments

```Shell
--xformers --medvram

i have **not** changed the cmd argument the arguments
```

### Console logs

```Shell
https://pastebin.com/dkUBhErV
```

**Comment by LordHellscream** [comment]
Ok updated the extension, restart SD, and was able to get a simply prompt in, but when i tried my old prompt (this one ive done numerous of time i again start hitting this error)
Here is the log
https://pastebin.com/CdCxFSSD

**Comment by zappityzap** [comment]
Please share the prompt and AnimateDiff settings that trigger the problem.

**Comment by LordHellscream** [comment]
[> Please share the prompt and AnimateDiff settings that trigger the problem.
prompts:
https://pastebin.com/QnyfzaqV

settings:
https://imgur.com/e7SQgfA

**Comment by zappityzap** [comment]
I can reproduce this when using a prompt travel line for frame 24 and the number of frames is 24 (or less). Prompt travel frames numbers start counting from zero rather one, so use 23 if you want that prompt travel line to be the last frame of 24:
```
(best quality), photograph, katiemcbride ,1girl, (cute scientist), (expressionless), (lab coat:1.4), mecha, complex biomechanical body, ultra sharp focus <lora:insanobot:1> <lora:wowifierV3:0.7> (small breasts), (warm lighting)
0: (eyes closed:1.3)
8: (frown:1.3)
16: (red iris:1.3), (smile:0.8)
23: (red iris:1.3), (red laser shooting out from eyes:0.9), (cyborg terminator face:1.3)
```
It looks like parse_prompt() in animatediff_prompt.py should validate the frame numbers. I'll submit a PR.

**Comment by LordHellscream** [comment]
Looks like my controlnet installation is bugged, replacing it seems to have fixed the issue.

**Comment by LordHellscream** [comment]
Ok it seems to be an real issue, reopened and let you resolve this.
