### ISSUE TITLE
[Feature]:  I found that the number of frames affects how much the color turns gray,我发现帧数会影响图片变灰程度

### ISSUE THREAD

**Issue by sdqq1234** [continue-revolution/sd-webui-animatediff#40]
### Expected behavior

I use same promts and seed and set different frames  result:

set 1 frame
![00005-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/ed1a3d0b-0245-4730-abc4-ea3e620f96b9)

set 2 frames:
![00006-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/64db6737-ed0a-48c5-9d87-2f7e60dd716f)

set 4 frames:
![00007-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/8bf347e4-bc9a-4f9b-b376-275a1259240d)

set 8 frames:
![00009-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/fe00047f-1ed2-461a-967f-c5c5c8ed469a)

set 20 frames:
![00011-1786350809](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/9848b79b-e6b9-45e7-aa35-7630a5326622)

and this is the result of not using animatediff:
![00295-1786350809-masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flo](https://github.com/continue-revolution/sd-webui-animatediff/assets/6040274/e058d026-1c1d-4b90-b58a-113c9851e226)

Maybe these can help you

**Comment by continue-revolution** [comment]
grey issue for DDIM shuold have been resolved. not sure for other samplers
