### ISSUE TITLE
[Bug]: 2.0 is broken on v2v and I have double LCM causing all normal gens to be washed out in master.

### ISSUE THREAD

**Issue by Ph0rk0z** [continue-revolution/sd-webui-animatediff#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I have been pulling on automatic1111 dev and one day saw 2 LCM samplers. Confused, I found that the PRs for LCM were merged into A1111 and saw you also modified the 2.0 branch.

I go to install the 2.0 branch and there are errors, in v2v it wasn't fixed when your removed the controlnet hacks. Now I have the issue where I get washed out gif/video on master without LCM lora and errors in the console and inability to get a generated video on 2.0. I don't even use v2v.

### Steps to reproduce the problem

use latest, make a gif

### What should have happened?

normal behavior

### Commit where the problem happens

webui: git
extension: 2.0
https://github.com/continue-revolution/sd-webui-animatediff/commit/1e57dda70d79eaf56350e93559c4379c7b64822f

### Command Line Arguments

```Shell
no ffs
```

### Console logs

```Shell
as described
```

**Comment by continue-revolution** [comment]
You are not supposed to use 2.0 for now and I’ve not finished working on it. The update for 2.0 is non-trivial - you need A1111 dev branch, ControlNet new version (still work in progress) and AnimateDiff new version (work in progress). If you want to try SparseCtrl, you should checkout specific commits in CN and AD (pls visit the corresponding PR page)

**Comment by Ph0rk0z** [comment]
I just want my gifs to not be washed out. The reason I bothered to use 2.0 is because double LCM breaks things on dev and not really itching to go back to old "stable" of A1111.

**Comment by continue-revolution** [comment]
I see. ‘Double LCM’ is actually my PR. I will create a “no lcm” branch in a few hours and you can use that branch as a workaround.

**Comment by Ph0rk0z** [comment]
Well.. I did all that.. and still I get a washed out image without LCM. In the console I only see a warning missing keys now.

**Comment by Ph0rk0z** [comment]
![IMG_20240124_103506](https://github.com/continue-revolution/sd-webui-animatediff/assets/59298527/22ab89df-8885-4ea2-a44b-102aed1bdf31)

Example

**Comment by JustCann** [comment]
I have the same issue, so is LCM not possible without being completely washed?

**Comment by continue-revolution** [comment]
might have been fixed. if not let me know
