### ISSUE TITLE
[Feature]: T2I Adapter Support 

### ISSUE THREAD

**Issue by JustCann** [continue-revolution/sd-webui-animatediff#414]
### Expected behavior

Hello,

I may be doing this incorrectly, but when I attempt to use T2I Adapters in CN the extension creates an animated gif but keeps the model frozen in place as if I was doing img2img. Is using T2I Adapters supported or am I doing something incorrectly?

Thanks!!

**Comment by dariiboi** [comment]
seconding this! 
I've had the same experience

**Comment by continue-revolution** [comment]
Today I tested t2i-adapter and found that it was working "properly", but the generation is far worse than the ControlNet equivalency. Here I offer 2 samples, and the only difference is one use T2IAdapter and another use ControlNet
| T2I Adapter | ControlNet |
| --- | --- |
| ![00004-3010576036](https://github.com/continue-revolution/sd-webui-animatediff/assets/63914308/266df62a-ef53-4253-b7c6-7af810e3258d) | ![00005-1961300716](https://github.com/continue-revolution/sd-webui-animatediff/assets/63914308/ac071ccb-8354-4b9c-a2a0-a573b61e8f4f) |

I don't know if there was a bug or something, but I would strongly recommend using ControlNet.
