### ISSUE TITLE
[Bug]: IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

### ISSUE THREAD

**Issue by jukyfdv** [continue-revolution/sd-webui-animatediff#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [x] I have updated WebUI and this extension to the latest version

### What happened?

When using ControlNet of single image to v2v, I entered the folder containing the subfolder `image` and `mask` in the batch. This problem seems to have existed for several months.I found two other friends mentioned this issue in issues, but there was no follow-up, so I had to ask again. I hope the author can fix it soon, thank you!Using inpaint_global_harmonious can output normally. If I use inpaint_only and inpaint_only+lama, the error will occur.My purpose is to process only part of the image of the mask, inpaint_global_harmonious cannot meet my requirements.
```
*** Error running process:stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 499, in hacked_main_entry
        final_inpaint_mask = final_inpaint_feed[0, 3, :, :].astype(np.float32)
    IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

---
```

### Steps to reproduce the problem

When using ControlNet of single image to v2v, I entered the folder containing the subfolder `image` and `mask` in the batch.If I use inpaint_only and inpaint_only+lama, the error will occur

### What should have happened?

Only the mask part is processed, but an error is reported.

### Commit where the problem happens

webui: [v1.7.0]
extension:  ControlNet v1.1.430
                  sd-webui-animatediff  [v1.13.1]

### Command Line Arguments

```Shell
--opt-sdp-attention --no-half-vae --disable-nan-check --disable-safe-unpickle
```

### Console logs

```Shell
none
```

**Comment by continue-revolution** [comment]
inpaint problem should no longer exist. I will update doc in a day. close it for now
