### ISSUE TITLE
[Feature]: How do I use the API to call this function? thanks.

### ISSUE THREAD

**Issue by bieyongdapaodawenzi** [continue-revolution/sd-webui-animatediff#42]
### Expected behavior

payload = {
        "prompt": aPrompt,
        "negative_prompt": aNprompt,
        "width": 512,
        "height": 768,
        "steps": 25,
        "sampler_index": "Euler a"
    }

response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

------------------------------------
This is a request to call a txt2img, but I'm not sure how to call "AnimateDiff" here to generate an animation. thanks

**Comment by bluewayg** [comment]
"alwayson_scripts":{"AnimateDiff": {"args": [true,0,24,6,"mm_sd_v15.ckpt"]}
