### ISSUE TITLE
[Bug]: GIFs not working in telegram

### ISSUE THREAD

**Issue by Yaeph** [continue-revolution/sd-webui-animatediff#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

GIF's created through [sd-webui-animatediff] are not working in telegram. Only after I push it through photoshop (or any other method of gif re-making) it starts playing like normal.

### Steps to reproduce the problem

1. Make a GIF in automatic1111 with [sd-webui-animatediff] enabled,
2. Send it to someone on telegram
3. For both sides GIF is just a static picture, and it requires to go to files and check it manually.

### What should have happened?

Normally it should just be a normal GIF,

### Commit where the problem happens

webui:  , automatic1111

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
any, really.
```

### Console logs

```Shell
there is no errors.
```

### Additional information

My guess, it is related to GIF's format, something is missing or corrupted inside GIF and some devices plays it normally, some (telegram, for example) are not.

**Comment by continue-revolution** [comment]
Today I sent the gif to my friend via TG and it worked properly. I believe that this issue has been resolved.
