### ISSUE TITLE
[Bug]: EinopsError: Error while processing rearrange-reduction pattern "(b f) d c -> (b d) f c". Input tensor shape: torch.Size([2, 8040, 320]). Additional info: {'f': 16}. Shape mismatch, can't divide axis of length 2 in chunks of 16

### ISSUE THREAD

**Issue by thinhducng202** [continue-revolution/sd-webui-animatediff#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

EinopsError: Error while processing rearrange-reduction pattern "(b f) d c -> (b d) f c". Input tensor shape: torch.Size([2, 8040, 320]). Additional info: {'f': 16}. Shape mismatch, can't divide axis of length 2 in chunks of 16

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

123

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
123
```

### Console logs

```Shell
123
```

**Comment by continue-revolution** [comment]
how can you produce this error? there is no way for me to produce such error.

**Comment by thinhducng202** [comment]
> how can you produce this error? there is no way for me to produce such error.

I do not know,Deleting and downloading again doesn't work

**Comment by continue-revolution** [comment]
screenshot your ui

**Comment by thinhducng202** [comment]
> chụp màn hình giao diện người dùng của bạn
![Screenshot 2024-03-06 155711](https://github.com/continue-revolution/sd-webui-animatediff/assets/135584552/4c7b0dde-15b6-4f84-a90c-5e3dab7d2737)

**Comment by continue-revolution** [comment]
I mean WebUI

**Comment by thinhducng202** [comment]
> Ý tôi là WebUI

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/135584552/09615a2b-b250-4557-a534-e3be0a1ecb48)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/135584552/1a34d7fa-891e-44b1-ba7c-bde171b5f418)

**Comment by continue-revolution** [comment]
everything, including other parts on your t2i panel.

**Comment by continue-revolution** [comment]
you must be using whatever other extension that attempt to change batch size after me. please do not use dynamic prompt

**Comment by thinhducng202** [comment]
> mọi thứ, kể cả các phần khác trên bảng điều khiển t2i của bạn.

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/135584552/88dfd753-e14a-43fb-968d-3f6cafa4bb6f)

**Comment by continue-revolution** [comment]
wow, these are so old. update everything and retry. WebUI, ControlNet, AnimateDiff

**Comment by thinhducng202** [comment]
> ồ, những thứ này cũ quá rồi. cập nhật mọi thứ và thử lại. WebUI, ControlNet, AnimateDiff

Thank you, problem has been resolved

**Comment by DHG-Dav** [comment]
i have the same problem
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/d77a5b54-3001-4ff8-a869-36a00207495b)
Fresh install of last version of webui, installed only controlnet and animatediff, animatediff works if i don't enable controlnet, but whatever settings i change in controlnet i get the error if i enable it.
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/edb91ccd-5dd3-448a-9345-c326e20926ab)

**Comment by continue-revolution** [comment]
please give **full** screenshot, include everything in your frontend. also give me a **full** terminal log

**Comment by DHG-Dav** [comment]
![010051](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/e3f4fab4-7f52-4b27-bb31-d3358bc5a2a5)
![010053](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/610266c2-8017-471f-99ad-7a69c0558a81)
![010056](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/dd549a53-7735-49a2-947d-57187a247924)
![010057](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/897fa29b-c15c-4e00-b25b-7b46efb59c07)
![010058](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/e8c6d473-9df6-489c-bf4c-2ab09acc3d5f)
![010059](https://github.com/continue-revolution/sd-webui-animatediff/assets/95366910/8336cb29-3150-448e-8222-8cbb22d3ec72)

**Comment by continue-revolution** [comment]
the video extraction is buggy. please try #450 if you can do git. If you cannot do git, wait for a day and I will update to 2.0.1-a and fix this.

**Comment by continue-revolution** [comment]
nvm I merged #450. Please update your AnimateDiff and retry.

**Comment by DHG-Dav** [comment]
ok, thank you for your fast-as-light reaction time ^^

**Comment by DHG-Dav** [comment]
and it now works !

**Comment by continue-revolution** [comment]
this has nothing to do with AnimateDiff, but more seem like a hardware issue. Most likely you need to restart your computer.

**Comment by DHG-Dav** [comment]
but i have no issue with anything else than animatediff though, if i disable animatediff i can generate 2000px pictures flawlessly

**Comment by continue-revolution** [comment]
paste everything here - the screenshot of your webui, your full terminal log

**Comment by DHG-Dav** [comment]
nevermind, i gave up, thank you for your help though, wish you the best.
