### ISSUE TITLE
Grey issue fix = Crank that CFG (workaround)

### ISSUE THREAD

**Issue by Mousewrites** [continue-revolution/sd-webui-animatediff#45]
I found that if you really crank the cfg (i'm talking, 17-25), the greyout issue diminishes, but the image DOESN'T burn to a crisp like they would if you just did a normal txt2img with that high a cfg.

I'm sure there's going to be a more elegant solution, but it works.

Thanks for the extension, i couldn't get the main project working. :D

**Comment by continue-revolution** [comment]
The grey issue should have been resolved in the new update v1.3.0 for DDIM sampler.
