### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XiaoCC** [continue-revolution/sd-webui-animatediff#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/7299222/d9b5a12a-df2c-4ec3-b58c-98854b9a3b61)
1. 负面提示词加入Embedding 就会照成生成的动画分成2段 不连续的GIF

### Steps to reproduce the problem

1. 负面提示词加入Embedding 就会照成生成的动画分成2段 不连续的GIF

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/7299222/0295e09d-e0c0-4150-b1ba-5f389b4fd892)

### What should have happened?

1. 负面提示词加入Embedding 就会照成生成的动画分成2段 不连续的GIF，应该生成相关联的GIF

### Commit where the problem happens

webui: 1.5.1
extension: 1.2.1

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
none
```

**Comment by XiaoCC** [comment]
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/7299222/e71e3122-4520-4aa7-8da2-97f7c8278c80)

**Comment by ArnorWing** [comment]
I had this problem and after i disabled Dynamic Thresholding (CFG Scale Fix) it stopped.  I haven't tried again since the update today

**Comment by Lorek772** [comment]
This might be an issue with a negative promting

**Comment by continue-revolution** [comment]
#83
