### ISSUE TITLE
[Feature]: what the model using for the web page?

### ISSUE THREAD

**Issue by SherlockSunset** [continue-revolution/sd-webui-animatediff#460]
### Expected behavior

Hi, just want to thanks for the great work! May I know what models you are using for the web: https://www.animatediff.org/, the style looks great.

**Comment by continue-revolution** [comment]
This website has nothing to do with me, also has  nothing to do with the original authors from Shanghai AI Lab. I don't know who build it.

The model looks like https://civitai.com/models/30240/toonyou, but there is no guarantee.
