### ISSUE TITLE
[Feature]: surport   AnimateDiff-Lightning

### ISSUE THREAD

**Issue by zhangjianzoujianghu18** [continue-revolution/sd-webui-animatediff#478]
### Expected behavior

 AnimateDiff-Lightning is a fast text-to-video generation model, I'd like to use it on the extension. 
 so, how can I do it.

**Comment by continue-revolution** [comment]
Why not just try using it directly? The model architecture should be the same as ad-v2. Since comfyui AnimateDiff node is derived from this software, you can try using the comfyui model first. If it’s not working, re-open this issue and let me know.
