### ISSUE TITLE
[Feature]: 输出结果gif和mp4在界面不显示

### ISSUE THREAD

**Issue by wly-ai-bj** [continue-revolution/sd-webui-animatediff#481]
### Expected behavior

正常运行，在output文件夹下有结果，但是在webui的输出界面中不显示，是为什么？
<img width="709" alt="image" src="https://github.com/continue-revolution/sd-webui-animatediff/assets/58155968/fdeccb0b-9d68-4b5f-80ca-2d038fb109f8">

**Comment by continue-revolution** [comment]
Gradio前端无法显示mp4，gif可以正常显示。尝试取消勾选mp4，应该可以在前端看到输出。
