### ISSUE TITLE
[Bug]: AnimateDiff - WARNING - No motion module detected

### ISSUE THREAD

**Issue by ununiform** [continue-revolution/sd-webui-animatediff#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I have the models installed in /Users/[ME]/stable-diffusion-webui/extensions/sd-webui-animatediff/model But I'm getting the error:

AnimateDiff - WARNING - No motion module detected, falling back to the original forward. You are most likely using !Adetailer. !Adetailer post-process your outputs sequentially, and there will NOT be motion module in your UNet, so there might be NO temporal consistency within the inpainted face. Use at your own risk. If you really want to pursue inpainting with AnimateDiff inserted into UNet, use Segment Anything to generate masks for each frame and inpaint them with AnimateDiff + ControlNet. Note that my proposal might be good or bad, do your own research to figure out the best way.

I'm not using ADetailer

### Steps to reproduce the problem

I've installed the models and try to generate a 4 frame animation. No luck. Error appears upon clicking Generate

### What should have happened?

I was expecting it to render 4 frames using Animatediff. This is my first time so I'm not sure what to expect.

### Commit where the problem happens

webui: automatic1111
extension: AnimateDiff

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
None. No errors in console
```

**Comment by zappityzap** [comment]
Please share the entire output of the console.

**Comment by Smith15hypeh** [comment]
2024-05-06 21:56:11,852 - AnimateDiff - WARNING - No motion module detected, falling back to the original forward. You are most likely using !Adetailer. !Adetailer post-process your outputs sequentially, and there will NOT be motion module in your UNet, so there might be NO temporal consistency within the inpainted face. Use at your own risk. If you really want to pursue inpainting with AnimateDiff inserted into UNet, use Segment Anything to generate masks for each frame and inpaint them with AnimateDiff + ControlNet. Note that my proposal might be good or bad, do your own research to figure out the best way.

0: 640x640 1 hand, 14.0ms
Speed: 4.0ms preprocess, 14.0ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)
2024-05-06 21:56:16,786 - AnimateDiff - WARNING - No motion module detected, falling back to the original forward. You are most likely using !Adetailer. !Adetailer post-process your outputs sequentially, and there will NOT be motion module in your UNet, so there might be NO temporal consistency within the inpainted face. Use at your own risk. If you really want to pursue inpainting with AnimateDiff inserted into UNet, use Segment Anything to generate masks for each frame and inpaint them with AnimateDiff + ControlNet. Note that my proposal might be good or bad, do your own research to figure out the best way.
2024-05-06 21:56:20,469 - AnimateDiff - INFO - AnimateDiff process start.
2024-05-06 21:56:20,482 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet input blocks.
2024-05-06 21:56:20,482 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet output blocks.
2024-05-06 21:56:20,483 - AnimateDiff - INFO - Setting DDIM alpha.
2024-05-06 21:56:20,487 - AnimateDiff - INFO - Injection finished.
2024-05-06 21:56:20,487 - AnimateDiff - INFO - AnimateDiff + ControlNet will generate 16 frames
AnimateDiff - WARNING - prompt is not str, cannot support prompt map

I have installed two required  motion module. Whether I use the !Adetailer or not,the error still exists. I don't know why.

**Comment by ununiform** [comment]
I'm experiencing the same issue. The motion modules are in the correct folder. I'm not using ADetailer.

If you find a solution, please share.

**Comment by zappityzap** [comment]
I saw this error come up when attempting to use an SDXL checkpoint with a non-SDXL motion module. The actual error was in the console log above the errors that have been shared here.

**Comment by ununiform** [comment]
Loading weights [cc6cb27103] from /Users/jaygarett/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
Applying attention optimization: sub-quadratic... done.
Weights loaded in 2.7s (send model to cpu: 0.6s, load weights from disk: 0.9s, apply weights to model: 0.5s, move model to device: 0.7s).
2024-05-26 17:54:39,448 - AnimateDiff - INFO - AnimateDiff process start.
*** Error running before_process: /Users/jaygarett/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/Users/jaygarett/stable-diffusion-webui/modules/scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "/Users/jaygarett/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 64, in before_process
        motion_module.inject(p.sd_model, params.model)
      File "/Users/jaygarett/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_mm.py", line 76, in inject
        elif self.mm.enable_gn_hack():
      File "/Users/jaygarett/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'MotionWrapper' object has no attribute 'enable_gn_hack'

---
  0%|                                                                                                                                                                                                                                                                   | 0/30 [00:00<?, ?it/s]2024-05-26 17:54:39,961 - AnimateDiff - WARNING - No motion module detected, falling back to the original forward. You are most likely using !Adetailer. !Adetailer post-process your outputs sequentially, and there will NOT be motion module in your UNet, so there might be NO temporal consistency within the inpainted face. Use at your own risk. If you really want to pursue inpainting with AnimateDiff inserted into UNet, use Segment Anything to generate masks for each frame and inpaint them with AnimateDiff + ControlNet. Note that my proposal might be good or bad, do your own research to figure out the best way.

*****!!!!!!!
I'm not using ADetailer

**Comment by Rogue-si** [comment]
Getting the same error after a restart, Everything worked prior to the restart of the computer, same error message:

AnimateDiff - WARNING - No motion module detected, falling back to the original forward. You are most likely using !Adetailer. !Adetailer post-process your outputs sequentially, and there will NOT be motion module in your UNet, so there might be NO temporal consistency within the inpainted face. Use at your own risk. If you really want to pursue inpainting with AnimateDiff inserted into UNet, use Segment Anything to generate masks for each frame and inpaint them with AnimateDiff + ControlNet. Note that my proposal might be good or bad, do your own research to figure out the best way.

**Comment by zappityzap** [comment]
Can't troubleshoot without details. Need the full console log from the moment the application is launched, versions of software, generation settings, and any other steps needed to reproduce the error.

**Comment by Eeeeano** [comment]
Had the same problem. Couldn't find the cause.
I reinstalled the webUI and the problem was solved.

**Comment by Chadius** [comment]
I ran into the same problem, I think the module does not recurse down folders. Make sure you save the module in the ` /Users/[ME]/stable-diffusion-webui/extensions/sd-webui-animatediff/model` directory, not an subdirectories.

I saved mm_sd15_v3.safetensors into ` /Users/[ME]/stable-diffusion-webui/extensions/sd-webui-animatediff/model/sd15/mm` so it's easier to read a list and identify the main components. But the stable-diffusion dropdown doesn't recurse through subdirectories, so it couldn't find the module and gave me the same error as above.

Here's a screenshot of the dropdown once I copied the module directly. Notice how it's showing `sd15` instead of `sd15/mm/mm_sd15_v3.safetensors`:

<img width="706" alt="Screenshot 2024-09-21 at 07 04 15" src="https://github.com/user-attachments/assets/3e88f290-ceb9-43c0-9557-eaabf59e2e0b">

If you're still stuck, try putting the module in the bare directory. The directory could attempt a recursive walk to find checkpoints and safetensors files.

**Comment by zappityzap** [comment]
Thanks, I submitted a PR for this.

**Comment by wood-123456** [comment]
def generate_image(prompt, api_url, user_batch_size, frame, max_frame):
    payload = {
        "prompt": prompt,
        "steps": 50,
        "width": 512,
        "height": 512,
        "n_iter": user_batch_size,
        "sd_model_checkpoint": CHECKPOINT_PATH,
        "lora": [LORA_PATH],
        "alwayson_scripts": {
            "ADetailer": {
                "args": [
                    {"ad_model": "face_yolov8s.pt"},
                    {"ad_model": "hand_yolov8n.pt"}
                ]
            },
            "AnimateDiff": {
                "args": [
                    {"enable": True},
                    {"model": "mm_sd_v15_v2.safetensors"},
                    {"batch_size": 30},
                    {"format": ["GIF"]},
                    {"loop_number": 0},
                    {"stride": 1},
                    {"closed_loop": "R+P"},
                    {"overlap": -1},
                    {"interp":"off"},
                    {"video_length": max_frame},
                    {"fps": frame}
                ]
            }
        }
    }

    try:
        response = requests.post(api_url, json=payload)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"生成圖像出錯: {e}")
        return None        this is my code i have same problem 
![image](https://github.com/user-attachments/assets/c5505983-1bd4-42b3-a521-2b807f8af75c)

**Comment by wood-123456** [comment]
![image](https://github.com/user-attachments/assets/7e7acf85-2876-4147-9e9e-8ccf36ac672b)

**Comment by wood-123456** [comment]
the chininse in the command is engilish ,not input error

**Comment by zappityzap** [comment]
Please check automatic1111 settings for AnimateDiff extension "Path to save AnimateDiff motion modules"

There may be additional clues in the console output before the part you shared.

**Comment by mendigy** [comment]
> Please check automatic1111 settings for AnimateDiff extension "Path to save AnimateDiff motion modules"
> 
> There may be additional clues in the console output before the part you shared.

This work around solve the problem!

**Comment by Quest79** [comment]
lol How can it detect the modules are there so it shows up in a dropdown menu and not detect them at the same time. Thats some wild shit

**Comment by mine251208-debug** [comment]
*** Error loading script: animatediff_ui.py
    Traceback (most recent call last):
      File "C:\Users\lehie\Downloads\forge--\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\lehie\Downloads\forge--\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\lehie\Downloads\forge--\webui\extensions\sd-forge-animatediff\scripts\animatediff_ui.py", line 12, in <module>
        from scripts.animatediff_mm import mm_animatediff as motion_module
      File "C:\Users\lehie\Downloads\forge--\webui\extensions\sd-forge-animatediff\scripts\animatediff_mm.py", line 5, in <module>
        from modules_forge.unet_patcher import UnetPatcher
    ModuleNotFoundError: No module named 'modules_forge.unet_patcher'

**Comment by necropower** [comment]
how did you fix the ldm problem? i got this problem that you got too
