### ISSUE TITLE
[Bug]: 怎么回退到昨天的版本？今天更新的版本根本用不了

### ISSUE THREAD

**Issue by 2575044704** [continue-revolution/sd-webui-animatediff#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

无法运行，不能用了

### Steps to reproduce the problem

运行SD
报错No module named "scripts.animatediff_mm"

### What should have happened?

不想用这个插件，总是出大bug。把我SD干死了，一整天都用不了
![Image_1713164858901](https://github.com/continue-revolution/sd-webui-animatediff/assets/19410065/f143975a-85a3-4bed-bd24-b8d616953942)

### Commit where the problem happens

webui: 1.8.0
extension: main

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
xformers
api
```

### Console logs

```Shell
见上面图片
```

**Comment by continue-revolution** [comment]
`git checkout v2.0.0-a`

the new version today `v2.0.0.1-a` is for A1111 WebUI v1.9.0. I am not sure what will happen if you use any previous version.
