### ISSUE TITLE
[Bug]: no options about [optimize attention layers with xforms] in settings

### ISSUE THREAD

**Issue by MerlinQu** [continue-revolution/sd-webui-animatediff#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

In Settings of AnimateDiff, there is no options about [optimize attention layers with xforms]
在设置中，我的AnimateDiff插件没有Xformers相关的优化选项
![xfomers](https://github.com/continue-revolution/sd-webui-animatediff/assets/167158630/605e8ed5-d427-4c39-9712-f1a6d00c26d6)
this is my ScrrenShot
这是我的截屏
![animateDiff](https://github.com/continue-revolution/sd-webui-animatediff/assets/167158630/66fae05e-afff-4178-ad6f-64ae5c239a8f)

### Steps to reproduce the problem

I confirm that pytorch and Xformers are installed and upgraded to the latest version
我确认已经安装pytorch和Xformers，并升级到了最新版本

### What should have happened?

When I use 1024x1024 to Generate 16 frames of animation，Cuda out of memory
So I start SD webui with --xformers , but it doesn't work

### Commit where the problem happens

webui: SD webui the latest version 1.9.0
extension: animateDiff

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no
```

**Comment by continue-revolution** [comment]
we have said goodbye to this option because we will always use scaled dot product attention from pytorch.

**Comment by continue-revolution** [comment]
the main reason is that there is only one tiny xformers version that won't throw error with animatediff

**Comment by MerlinQu** [comment]
> we have said goodbye to this option because we will always use scaled dot product attention from pytorch.

thanks for reply
in my settings, there is no options about [Optimize attention layers with sdp] either
how can I fix it ?  thank you
![SDP](https://github.com/continue-revolution/sd-webui-animatediff/assets/167158630/064459dd-d070-48fe-a719-032ed61564fc)

**Comment by continue-revolution** [comment]
we have removed this option. you can consider you are always at the option you circled

**Comment by MerlinQu** [comment]
> we have removed this option. you can consider you are always at the option you circled

I got it. Thank you.
