### ISSUE TITLE
[Bug]: animatediff cann't work

### ISSUE THREAD

**Issue by littleyeson** [continue-revolution/sd-webui-animatediff#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

![QQ截图20240418002657](https://github.com/continue-revolution/sd-webui-animatediff/assets/70052345/9c8a6c7b-8a3d-4f55-bad6-3138ac2279e4)
animatediff cann't work

### Steps to reproduce the problem

1. set v2 model

### What should have happened?

CUDA not run

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
log
```

**Comment by Raziel619** [comment]
Updating my GPU drivers fixed this error for me.

**Comment by littleyeson** [comment]
I find whet the token more than 75 It will be this problem. It must restart the webui and make sure the token less than 75.

**Comment by continue-revolution** [comment]
make sure to enable pad cond uncond

**Comment by linghu-cell** [comment]
> make sure to enable pad cond uncond
What does it mean?
