### ISSUE TITLE
[Feature]:AnimateDiff v2.0.0, AnimateDiff drawing style problem,The colours aren't quite right.

### ISSUE THREAD

**Issue by wf-ping** [continue-revolution/sd-webui-animatediff#514]
### Expected behavior

After getting a sheet of graphs from my text raw, fixed the seed, the
Using AnimateDiff, the animation generated colours aren't quite right.
The following are my AnimateDiff parameters, I did not use Lora, ControlNet, etc., and the forward and backward cues of the raw map were not modified.

# animatediff version
sd-forge-animatediff-2.0.0-f    from release
# my sd-webui-forge
webui-version : [f0.0.17v1.8.0rc-latest-276-g29be1da7]
python: 3.10.6  •
torch: 2.1.2+cu121  •
xformers: 0.0.23.post1  •
gradio: 3.41.2
checkpoint: [f1cf66d5b1]

# checkoutpoint
sweetSugarSyndrome_rev15.safetensors [f1cf66d5b1]

# AnimateDiff parameter
Motion module  : mm_sd15_v3.safetensors
Number of frames : 32
FPS:8
Display loop number：0
Stride:1
Overlap:-1
no video

# Here's the graph I got from the text2img,It's also the gif style I was expecting
![00034-380221765](https://github.com/continue-revolution/sd-webui-animatediff/assets/150904189/0ff0ad97-b34e-45ee-9d3c-e1dd1dbdca3b)

# This is one of the gifs generated

![00008-2423485594](https://github.com/continue-revolution/sd-webui-animatediff/assets/150904189/3c5f788d-bf41-4e26-9ad6-6c9cee9dcd72)

**Comment by wf-ping** [comment]
> ### 预期行为
> 从我的原始文本中获取一张图表后，修复了种子， 使用 AnimateDiff，动画生成的颜色不太正确。 以下是我的AnimateDiff参数，我没有使用Lora、ControlNet等，并且未修改原始地图的前进和后退线索。
> 
> # 结帐点
> sweetSugarSyndrome_rev15.safetensors [f1cf66d5b1]
> 
> # AnimateDiff 参数
> 运动模块：mm_sd15_v3.safetensors 帧数：32 FPS:8 显示循环数：0 步幅:1 重叠:-1 无视频
> 
> # 这是我从text2img得到的图，也是我期待的gif风格
> ![00034-380221765](https://private-user-images.githubusercontent.com/150904189/324458411-0ff0ad97-b34e-45ee-9d3c-e1dd1dbdca3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODk1OTUsIm5iZiI6MTcxMzc4OTI5NSwicGF0aCI6Ii8xNTA5MDQxODkvMzI0NDU4NDExLTBmZjBhZDk3LWIzNGUtNDVlZS05ZDNjLWUxZGQxZGJkY2EzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTQ3YzJkZmM0YWFhOTQ2YjQ3MmU5MDRjNjk4MGFmMjg1YThmMDZmNDQ5MjQzNTkyNTgyZmFkZjVjZmQ3MzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eO-MbGesZCbP4IZAD3DkbKP0xPaQl87nms7LajQpdNw)
> 
> # 这是生成的 gif 图像之一
> ![00008-2423485594](https://private-user-images.githubusercontent.com/150904189/324458944-3c5f788d-bf41-4e26-9ad6-6c9cee9dcd72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODk1OTUsIm5iZiI6MTcxMzc4OTI5NSwicGF0aCI6Ii8xNTA5MDQxODkvMzI0NDU4OTQ0LTNjNWY3ODhkLWJmNDEtNGUyNi05YWQ2LTZjOWNlZTlkY2Q3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTA1ZjhkZDZlMjgxNjQyNzFmMGI1ZGM4MzMwYzRjOTJjYmE5MTA5MDk3OTBiM2E1MmJiMDc5YzdjMzQxNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EWsJhV_YHs6Vb4QCx2jS97sjH5r9fu9NfK5Gkst_6FU) [ ![00008-2423485594](https://private-user-images.githubusercontent.com/150904189/324458944-3c5f788d-bf41-4e26-9ad6-6c9cee9dcd72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODk1OTUsIm5iZiI6MTcxMzc4OTI5NSwicGF0aCI6Ii8xNTA5MDQxODkvMzI0NDU4OTQ0LTNjNWY3ODhkLWJmNDEtNGUyNi05YWQ2LTZjOWNlZTlkY2Q3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTA1ZjhkZDZlMjgxNjQyNzFmMGI1ZGM4MzMwYzRjOTJjYmE5MTA5MDk3OTBiM2E1MmJiMDc5YzdjMzQxNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EWsJhV_YHs6Vb4QCx2jS97sjH5r9fu9NfK5Gkst_6FU) ](https://private-user-images.githubusercontent.com/150904189/324458944-3c5f788d-bf41-4e26-9ad6-6c9cee9dcd72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODk1OTUsIm5iZiI6MTcxMzc4OTI5NSwicGF0aCI6Ii8xNTA5MDQxODkvMzI0NDU4OTQ0LTNjNWY3ODhkLWJmNDEtNGUyNi05YWQ2LTZjOWNlZTlkY2Q3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTA1ZjhkZDZlMjgxNjQyNzFmMGI1ZGM4MzMwYzRjOTJjYmE5MTA5MDk3OTBiM2E1MmJiMDc5YzdjMzQxNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EWsJhV_YHs6Vb4QCx2jS97sjH5r9fu9NfK5Gkst_6FU) [ ](https://private-user-images.githubusercontent.com/150904189/324458944-3c5f788d-bf41-4e26-9ad6-6c9cee9dcd72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODk1OTUsIm5iZiI6MTcxMzc4OTI5NSwicGF0aCI6Ii8xNTA5MDQxODkvMzI0NDU4OTQ0LTNjNWY3ODhkLWJmNDEtNGUyNi05YWQ2LTZjOWNlZTlkY2Q3Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMjM0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTA1ZjhkZDZlMjgxNjQyNzFmMGI1ZGM4MzMwYzRjOTJjYmE5MTA5MDk3OTBiM2E1MmJiMDc5YzdjMzQxNGYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EWsJhV_YHs6Vb4QCx2jS97sjH5r9fu9NfK5Gkst_6FU)

**Comment by continue-revolution** [comment]
unfortunately, the artifact introduced by motion module is inevitable, and I have no way to deal with it
