### ISSUE TITLE
[Bug]: Error loading script: animatediff_output.py and animatediff.py

### ISSUE THREAD

**Issue by alieverlove** [continue-revolution/sd-webui-animatediff#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Please Help us 
after Installed animatediff .
Animatediff did not appears on web ui. 

and this error
venv "H:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.4
Commit hash: feee37d75f1b168768014e4634dcb156ee649c05
Requirement already satisfied: ultralytics>=8.2.0 in h:\stable-diffusion-webui\venv\lib\site-packages (8.2.28)
Requirement already satisfied: scipy>=1.4.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (1.11.3)
Requirement already satisfied: tqdm>=4.64.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (4.66.1)
Requirement already satisfied: py-cpuinfo in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (9.0.0)
Requirement already satisfied: matplotlib>=3.3.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (3.8.1)
Requirement already satisfied: torchvision>=0.9.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (0.15.2+cu118)
Requirement already satisfied: torch>=1.8.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (2.0.1+cu118)
Requirement already satisfied: opencv-python>=4.6.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (4.10.0.82)
Requirement already satisfied: requests>=2.23.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (2.31.0)
Requirement already satisfied: psutil in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (5.9.5)
Requirement already satisfied: pandas>=1.1.4 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (2.1.3)
Requirement already satisfied: seaborn>=0.11.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (0.13.0)
Requirement already satisfied: pyyaml>=5.3.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (6.0.1)
Requirement already satisfied: pillow>=7.1.2 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (9.5.0)
Requirement already satisfied: ultralytics-thop>=0.2.5 in h:\stable-diffusion-webui\venv\lib\site-packages (from ultralytics>=8.2.0) (0.2.7)
Requirement already satisfied: kiwisolver>=1.3.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (3.1.1)
Requirement already satisfied: packaging>=20.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (23.2)
Requirement already satisfied: numpy<2,>=1.21 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (1.26.2)
Requirement already satisfied: fonttools>=4.22.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (4.44.0)
Requirement already satisfied: python-dateutil>=2.7 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (2.8.2)
Requirement already satisfied: cycler>=0.10 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib>=3.3.0->ultralytics>=8.2.0) (1.2.0)
Requirement already satisfied: pytz>=2020.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.2.0) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from pandas>=1.1.4->ultralytics>=8.2.0) (2023.3)
Requirement already satisfied: idna<4,>=2.5 in h:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in h:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in h:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0) (2023.7.22)
Requirement already satisfied: urllib3<3,>=1.21.1 in h:\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.23.0->ultralytics>=8.2.0) (2.1.0)
Requirement already satisfied: jinja2 in h:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.2.0) (3.1.2)
Requirement already satisfied: filelock in h:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.2.0) (3.13.1)
Requirement already satisfied: sympy in h:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.2.0) (1.12)
Requirement already satisfied: typing-extensions in h:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.2.0) (4.12.1)
Requirement already satisfied: networkx in h:\stable-diffusion-webui\venv\lib\site-packages (from torch>=1.8.0->ultralytics>=8.2.0) (3.2.1)
Requirement already satisfied: colorama in h:\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.64.0->ultralytics>=8.2.0) (0.4.6)
Requirement already satisfied: six>=1.5 in h:\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics>=8.2.0) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in h:\stable-diffusion-webui\venv\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics>=8.2.0) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in h:\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch>=1.8.0->ultralytics>=8.2.0) (1.3.0)
current transparent-background 1.2.4
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.10.0.82 to 4.8.0
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: insightface==0.7.3 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from -r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.7.3)
Requirement already satisfied: onnx==1.14.0 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from -r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: onnxruntime==1.15.0 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from -r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: opencv-python==4.7.0.72 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from -r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 4)) (4.7.0.72)
Requirement already satisfied: ifnude in c:\users\aliever\appdata\roaming\python\python310\site-packages (from -r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 5)) (0.0.3)
Requirement already satisfied: cython in c:\users\aliever\appdata\roaming\python\python310\site-packages (from -r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 6)) (3.0.0)
Requirement already satisfied: numpy in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.26.4)
Requirement already satisfied: tqdm in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (4.66.4)
Requirement already satisfied: requests in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: matplotlib in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.9.0)
Requirement already satisfied: Pillow in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (10.3.0)
Requirement already satisfied: scipy in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: scikit-learn in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: scikit-image in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.23.2)
Requirement already satisfied: easydict in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.10)
Requirement already satisfied: albumentations in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: prettytable in c:\users\aliever\appdata\roaming\python\python310\site-packages (from insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.10.0)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from onnx==1.14.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 2)) (4.25.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from onnx==1.14.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 2)) (4.12.1)
Requirement already satisfied: coloredlogs in c:\users\aliever\appdata\roaming\python\python310\site-packages (from onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\aliever\appdata\roaming\python\python310\site-packages (from onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (23.5.26)
Requirement already satisfied: packaging in c:\users\aliever\appdata\roaming\python\python310\site-packages (from onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (24.0)
Requirement already satisfied: sympy in c:\users\aliever\appdata\roaming\python\python310\site-packages (from onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (1.11.1)
Requirement already satisfied: opencv-python-headless>=4.5.1.48 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from ifnude->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 5)) (4.8.0.74)
Requirement already satisfied: PyYAML in c:\users\aliever\appdata\roaming\python\python310\site-packages (from albumentations->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: qudida>=0.0.4 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from albumentations->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.0.4)
Requirement already satisfied: networkx>=2.8 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from scikit-image->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.3)
Requirement already satisfied: imageio>=2.33 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from scikit-image->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.34.1)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from scikit-image->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2024.5.22)
Requirement already satisfied: lazy-loader>=0.4 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from scikit-image->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.4)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from coloredlogs->onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: wcwidth in c:\users\aliever\appdata\roaming\python\python310\site-packages (from prettytable->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from requests->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from requests->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from requests->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from requests->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (2022.12.7)
Requirement already satisfied: joblib>=1.1.1 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from scikit-learn->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from scikit-learn->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from sympy->onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: colorama in c:\users\aliever\appdata\roaming\python\python310\site-packages (from tqdm->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: pyreadline3 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.15.0->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 3)) (3.4.1)
Requirement already satisfied: six>=1.5 in c:\users\aliever\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3->-r H:\stable-diffusion-webui\extensions\sd-webui-roop\requirements.txt (line 1)) (1.16.0)
Launching Web UI with arguments: --xformers --medvram --autolaunch --skip-version-check
[-] ADetailer initialized. version: 24.5.1, num models: 10
*** Error loading script: animatediff.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff.py", line 15, in <module>
        from scripts.animatediff_output import AnimateDiffOutput
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 6, in <module>
        import imageio.v3 as imageio
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\v3.py", line 3, in <module>
        from .core.imopen import imopen
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\imopen.py", line 4, in <module>
        from ..config import known_plugins
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\config\__init__.py", line 7, in <module>
        from .plugins import known_plugins, PluginConfig
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\config\plugins.py", line 3, in <module>
        from ..core.legacy_plugin_wrapper import LegacyPlugin
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 6, in <module>
        from .request import InitializationError, IOMode
    ImportError: cannot import name 'InitializationError' from 'imageio.core.request' (H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\request.py)

---
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 6, in <module>
        import imageio.v3 as imageio
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\v3.py", line 3, in <module>
        from .core.imopen import imopen
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\imopen.py", line 4, in <module>
        from ..config import known_plugins
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\config\__init__.py", line 7, in <module>
        from .plugins import known_plugins, PluginConfig
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\config\plugins.py", line 3, in <module>
        from ..core.legacy_plugin_wrapper import LegacyPlugin
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 6, in <module>
        from .request import InitializationError, IOMode
    ImportError: cannot import name 'InitializationError' from 'imageio.core.request' (H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\request.py)

---
ControlNet preprocessor location: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-06-08 02:37:16,894 - ControlNet - INFO - ControlNet v1.1.449
2024-06-08 02:37:17,464 - roop - INFO - roop v0.0.2
2024-06-08 02:37:17,549 - roop - INFO - roop v0.0.2
Loading weights [879db523c3] from H:\stable-diffusion-webui\models\Stable-diffusion\DreamShaper.safetensors
WARNING:py.warnings:H:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")

WARNING:py.warnings:H:\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)

WARNING:py.warnings:H:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(

WARNING:py.warnings:H:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(

Creating model from config: H:\stable-diffusion-webui\configs\v1-inference.yaml
2024-06-08 02:37:17,930 - ControlNet - INFO - ControlNet UI callback registered.
WARNING:py.warnings:H:\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py:408: GradioDeprecationWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  result_image = gr.outputs.Image(type='pil')

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 21.6s (prepare environment: 9.4s, import torch: 3.1s, import gradio: 1.0s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.7s, list SD models: 0.3s, load scripts: 4.6s, create ui: 1.0s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 3.7s (load weights from disk: 0.2s, create model: 0.9s, apply weights to model: 2.1s, calculate empty prompt: 0.4s).

### Steps to reproduce the problem

1.  open web ui user. bat
2.  Install animatediff from  https://github.com/continue-revolution/sd-webui-animatediff
3 . Reload web ui from 
4. open web ui again,
5.  and I got Error 

### What should have happened?

Web ui can work fine, but Animatediff did not appear on interface 

### Commit where the problem happens

webui: 1.9.4
extension: 
-Adetailer ,
-Controlnett
-Roop
-ultimate Upscale
-Temporalkit
-Ebysinth

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
*** Error loading script: animatediff_output.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 6, in <module>
        import imageio.v3 as imageio
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\v3.py", line 3, in <module>
        from .core.imopen import imopen
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\imopen.py", line 4, in <module>
        from ..config import known_plugins
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\config\__init__.py", line 7, in <module>
        from .plugins import known_plugins, PluginConfig
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\config\plugins.py", line 3, in <module>
        from ..core.legacy_plugin_wrapper import LegacyPlugin
      File "H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 6, in <module>
        from .request import InitializationError, IOMode
    ImportError: cannot import name 'InitializationError' from 'imageio.core.request' (H:\stable-diffusion-webui\venv\lib\site-packages\imageio\core\request.py)

---
ControlNet preprocessor location: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-06-08 02:37:16,894 - ControlNet - INFO - ControlNet v1.1.449
2024-06-08 02:37:17,464 - roop - INFO - roop v0.0.2
2024-06-08 02:37:17,549 - roop - INFO - roop v0.0.2
Loading weights [879db523c3] from H:\stable-diffusion-webui\models\Stable-diffusion\DreamShaper.safetensors
WARNING:py.warnings:H:\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")

Creating model from config: H:\stable-diffusion-webui\configs\v1-inference.yaml
2024-06-08 02:37:17,930 - ControlNet - INFO - ControlNet UI callback registered.
WARNING:py.warnings:H:\stable-diffusion-webui\extensions\TemporalKit\scripts\sd-TemporalKit-UI.py:408: GradioDeprecationWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  result_image = gr.outputs.Image(type='pil')

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 21.6s (prepare environment: 9.4s, import torch: 3.1s, import gradio: 1.0s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.7s, list SD models: 0.3s, load scripts: 4.6s, create ui: 1.0s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 3.7s (load weights from disk: 0.2s, create model: 0.9s, apply weights to model: 2.1s, calculate empty prompt: 0.4s).
```

**Comment by zappityzap** [comment]
The error is coming from imageio, not sd-webui-animatediff. It seems like there may be something wrong with your environment. Is this a clean install? If not, you might try removing the venv to do a clean install.

**Comment by alieverlove** [comment]
hi thnks for the answer . I just fixed it with Changed - "Changed import imageio.v3 as imageio to import imageio as imageio" - in "H:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_output.py", line 6

> The error is coming from imageio, not sd-webui-animatediff. It seems like there may be something wrong with your environment. Is this a clean install? If not, you might try removing the venv to do a clean install.
