### ISSUE TITLE
[Dumb Question] Batch prompting SDXL

### ISSUE THREAD

**Issue by NullEqualsZero** [continue-revolution/sd-webui-animatediff#539]
Well, this is awkward. I am trying animatediff with SDXL for the very first time. I want to do batch prompting. Usually with SD1.5, there is a nice box where I can have my batch prompts 
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/149534255/d8c37b78-4e1e-4798-8aab-a37fd9841dcb)
but on the sdxl version of the node I don't see it. Is the text_g and text_l the same thing as the one I am seeing in the sd1.5 version? Sorry for the stupid question.

**Comment by zappityzap** [comment]
This repo is for the A1111 extension, not ComfyUI.
