### ISSUE TITLE
[Feature]: Could you add a file/documents with examples of successful settings/prompts to reproduce?

### ISSUE THREAD

**Issue by StableInfo** [continue-revolution/sd-webui-animatediff#56]
### Expected behavior

I would like to have like 5-6 examples of good prompts/Settings that produce nice gifs (gifs that have motion and no blur etc)
It could help the user get used to the extension.
Thanks

**Comment by continue-revolution** [comment]
visit the original repo https://github.com/guoyww/AnimateDiff/ and https://github.com/talesofai/AnimateDiff for a list of possible prompts. My prompts are all from them.

Their prompts live in configs/prompts
