### ISSUE TITLE
[Bug]: VAE is NOT APPLIED when this extension (animateDiff) is used 

### ISSUE THREAD

**Issue by StableInfo** [continue-revolution/sd-webui-animatediff#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I was testing with the extention and discovered that the models that need VAE to give nice results (such as Cardos Anime V2), were not applying their VAE when the animatediff option was checked.

The following is an image generated withotu any VAE:
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/136593585/66feb4fd-f6cd-4742-a452-2770e8c4d2ea)

Now with the VAE vae-ft-mse-840000-ema-pruned.vae.ckpt :  
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/136593585/27d980e8-0722-4831-bdd2-fc1a25188449)

Gif made with animateDiff:
![00023-3478388474](https://github.com/continue-revolution/sd-webui-animatediff/assets/136593585/dcf671c1-9f5f-434d-839f-190ae8ef212c)

Can you fix this please:) ?
Thanks

### Steps to reproduce the problem

1.  Model is available in civitai https://civitai.com/models/25399?modelVersionId=43825
2. VAE: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors
3. To change VAE go to settings -> Stable diffusion-> select the VAE in the options, --> Apply settings.

### What should have happened?

Every frame should be as colorful as the image generated when the VAE is applied. Instead all the images of the gif was lacking the colors of the important VAE.

### Commit where the problem happens

webui: version: [v1.4.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f865d3e11647dfd6c7b2cdf90dde24680e58acd8)  
extension:  [19191b55](https://github.com/continue-revolution/sd-webui-animatediff/commit/19191b55aaf4fce8b0c32de3fdae94d7a1fbd530)

### Command Line Arguments

```Shell
Xformers.
```

### Console logs

```Shell
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:40<00:00,  1.60s/it]
2023-08-10 14:49:18,820 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.38<00:00,  1.54s/it]
2023-08-10 14:49:18,821 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2023-08-10 14:49:18,822 - AnimateDiff - INFO - Restoring GroupNorm32 forward function.
2023-08-10 14:49:18,822 - AnimateDiff - INFO - Removal finished.
2023-08-10 14:49:18,822 - AnimateDiff - INFO - Merging images into GIF.
2023-08-10 14:49:20,213 - AnimateDiff - INFO - AnimateDiff process end.

Nothing particular, although the following log is MISSING:
Loading VAE weights specified in settings: D:\...\automatic\models\Stable-diffusion\Models\vae-ft-mse-840000-ema-pruned.vae.ckpt
Applying attention optimization: Doggettx... done.
VAE weights loaded.

This is what I see when I dont use AnimateDiff.
```

### Additional information

masterpiece, best quality, colorful explosion in the clouds, majestic black luminescent fly in the sky , psychedelic, ink, splashing, futuristic, winds 
Negative prompt: (low quality, worst quality:1.3), easynegative, bad-hands-5
Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 3478388474, Size: 512x512, Model hash: f243aabb88, Model: cardosAnime_v20, Clip skip: 2, Version: v1.4.1

**Comment by zappityzap** [comment]
Are you sure it didn't load the VAE earlier? In my experience it only shows those log lines when launching or when the VAE is switched, not on every generation. There's definitely something causing muted or dull outputs though.

**Comment by rkfg** [comment]
Couple of things to try:
1) Try running with the DDIM sampler
2) If it's much more colorful for you, try now with your usual sampler (DPM I suppose)
3) If it's better now, try applying this patch:
```diff
diff --git a/scripts/animatediff.py b/scripts/animatediff.py
index dec25ca..f61ea3a 100644
--- a/scripts/animatediff.py
+++ b/scripts/animatediff.py
@@ -197,8 +197,7 @@ class AnimateDiffScript(scripts.Script):
             assert video_length > 0 and fps > 0, "Video length and FPS should be positive."
             p.batch_size = video_length
             self.inject_motion_modules(p, model)
-            if p.sampler_name == "DDIM":
-                self.set_ddim_alpha(p)
+            self.set_ddim_alpha(p)
 
     def postprocess(self, p: StableDiffusionProcessing, res: Processed, enable_animatediff=False, loop_number=0, video_length=16, fps=8, model="mm_sd_v15.ckpt"):
         if enable_animatediff:
```
Looks like setting the DDIM parameters affect all other samplers too and it needs to be done on every generation, or rather for every model you load. I don't see any downsides and a big downside, the gray tint and noise disappear after applying this patch.

**Comment by StableInfo** [comment]
I am not used to patch on git, but this seems clears enough, I just need to find the animatediff.pyscript and replace the red lines with the green ones, did I get this right?
Also it's not just about a random "gray" tint, it's absolutely about **missing** a VAE, you can try the cardos anime model yourself and try to generate an image with and without the VAE I mentinoed and you will see.
I will try your fix and tell you if its works, thanks.

**Comment by continue-revolution** [comment]
Interesting @rkfg I just did a test and it really affects. Now in v1.4.1 it will always change beta.

**Comment by continue-revolution** [comment]
@StableInfo you should understand that VAE is a decoder which decode UNet latent to human-readable image, so there is always a VAE applied. The grey problem in images might be due to a broken VAE, and you need to use a new one to override the broken one. However, in this case, no matter you switch to whatever VAE you won't see any effect, then the reason is not about VAE. Also, this extension does not touch VAE, so the problem is certainly not about VAE.

**Comment by StableInfo** [comment]
"no matter you switch to whatever VAE you won't see any effect, then the reason is not about VAE. Also, this extension does not touch VAE, so the problem is certainly not about VAE." - @continue-revolution 

Yes, Hence the  title of my issue: The VAE (which is not broken) is NOT applied correclty then. Because the VAE works okay outside of animatediff. Cant wait to try the fix.

**Comment by rkfg** [comment]
Thanks for the donation, nice! 😊

**Comment by guardabrazo** [comment]
@StableInfo did you end up solving this? I'm having the same issue. VAE works just fine without animatediff but not when using it.

**Comment by StableInfo** [comment]
Donation?

**Comment by rkfg** [comment]
Yeah, I've got a tip to my Lightning address
