### ISSUE TITLE
Am I looking in the right place to find the model directory?

### ISSUE THREAD

**Issue by PortalTom** [continue-revolution/sd-webui-animatediff#6]
How do I access sd-webui-animatediff/model/ ?
Is it supposed to be in the following directory?
C:\Users\user\OneDrive\Desktop\stable-diffusion-webui

**Comment by JPW0080** [comment]
C:\Users\user\OneDrive\Desktop\stable-diffusion-webui\extensions\sd-webui-animatediff\model

mm_sd_v14.ckpt
mm_sd_v15.ckpt

**Comment by continue-revolution** [comment]
stable-diffusion-webui\extensions\sd-webui-animatediff\model
