### ISSUE TITLE
From the author: When will this repo be updated in the future?

### ISSUE THREAD

**Issue by continue-revolution** [continue-revolution/sd-webui-animatediff#64]
Hello everyone,

Since I am moving to the US, I have to prepare from last week till now, and I need to build a new PC. Amazon is still delaying its delivery for 3 days, and I have no idea when they will stop delaying. In the worst case, if my package is lost, you will have to wait until next weekend.

**Comment by Ainaemaet** [comment]
Thank you. 🙏
