### ISSUE TITLE
[Bug]: Just able to generate noise

### ISSUE THREAD

**Issue by BoXoBoXoBoXo** [continue-revolution/sd-webui-animatediff#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I can't generate anything other than noise. What did I miss?

![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/108448073/6984f162-a6b3-4289-8438-38b3c186b327)

### Steps to reproduce the problem

fresh install of automatic1111 , no other extensions

### What should have happened?

Something elese than noise

### Commit where the problem happens

webui: 
extension: 

### What browsers do you use to access the UI ?

Firefox

### Command Line Arguments

```Shell
?
```

### Console logs

```Shell
Nothing special... no errors here
```

### Additional information

OS: Windows 11 GPU: RTX 4070 (12 Go Vram)

**Comment by feiyangsuo** [comment]
bro did you solve this? got same problem
