### ISSUE TITLE
[Feature]: Support CLI prompt travel

### ISSUE THREAD

**Issue by continue-revolution** [continue-revolution/sd-webui-animatediff#71]
### Expected behavior

https://github.com/s9roll7/animatediff-cli-prompt-travel
- [x] controlnet
- [x] infinite context
- [x] batch cond uncond optional
- [x] prompt travel w/o ip-adapter
- [ ] prompt travel w/ ip-adapter
- [ ] reference only
- [ ] i2i batch
- [ ] [controlnet per-frame weights](https://cdn.discordapp.com/attachments/1145365129324675182/1161223403676631071/1399556488.mp4?ex=65378491&is=65250f91&hm=ca2aebbb71256347e2c1b139e699f937d6cbe347d47409063e41289a0c590baf&)
- [ ] test upscale

I think refine, tile-upscale and stylize can already be accompolished. If not, please follow up and let me know.

**Comment by continue-revolution** [comment]
Someone also sent me a bunch of links from
- https://twitter.com/toyxyz3
- https://twitter.com/TDS_95514874
I may want to read their post later to see what could be added.

**Comment by continue-revolution** [comment]
https://github.com/talesofai/AnimateDiff

This might also worth looking, but have to resolve img2img problem first.

**Comment by Gg811218** [comment]
加油

**Comment by continue-revolution** [comment]
Also find a way to automate the process of taking the last frame of a given gif (the last png in the sequence) and automatic continuing the generation through img2vid for longer videos, per request from @Ainaemaet

**Comment by continue-revolution** [comment]
also need to support other attention optimizations such as sdp

**Comment by Ainaemaet** [comment]
I suppose what we want here is prompt travel and not CLI-prompt travel lol.  

I will make separate requests as suggested - can't thank you enough, have you considered setting up a Patreon or something? I would gladly subscribe and I'm sure it would do quite well.

**Comment by continue-revolution** [comment]
Not really, CLI travel also supports ControlNet, which is something I also consider to support in the near future.

Yes, I can setup a patreon or something. Thanks for your support. I will update in README sponsor part.

**Comment by continue-revolution** [comment]
@Ainaemaet I have set up a Paypal QR code [here](https://github.com/continue-revolution/sd-webui-animatediff#sponsor). Let me know if this works.

**Comment by Ainaemaet** [comment]
@continue-revolution Sounds good, I will gladly donate when I can - would offer the suggestion to put the QR code in the UI somewhere :)  

I'm having an absolute blast with all of this; haven't bothered with Pika or Runway in weeks lol.

**Comment by continue-revolution** [comment]
This issue will be closed. Instead I will track my progress in each PR, such as https://github.com/continue-revolution/sd-webui-animatediff/pull/187#issue-1931713613
