### ISSUE TITLE
[Feature]: A suggestion for animatediff for the controlnet to connect, of course with video and GIF.

### ISSUE THREAD

**Issue by Mistermango23** [continue-revolution/sd-webui-animatediff#76]
### Expected behavior

My suggestion would be to connect controlnet to animatediff and generate an animation video. That's why need a video or a GIF to make inputs and then set it with controlnet, it also applies to animatediff and then generate an image animation and you're done. INFO: Of course I once saw what they did on comfyui because of controlnet and animatediff to make real animation.

Question is, can you make a script of this for controlnet? I will be very happy about that if possible. 

https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved

**Comment by continue-revolution** [comment]
#134
