### ISSUE TITLE
[Feature]: A new update of new animation motion models!

### ISSUE THREAD

**Issue by Mistermango23** [continue-revolution/sd-webui-animatediff#77]
### Expected behavior

https://huggingface.co/guoyww/animatediff/tree/main

a new model motion from "mm_sd_v15_v2.ckpt" and yeah, that's it.

**Comment by Mistermango23** [comment]
@continue-revolution 

New update Info: https://github.com/guoyww/AnimateDiff

**Comment by Mistermango23** [comment]
@continue-revolution 

ah yes, if you find anything, you will find it here of img2vid: https://github.com/ykk648/AnimateDiff.git

**Comment by Ainaemaet** [comment]
Yes, please add support for this mm_sd_v15_v2 model!!!  Currently using it just results in a grid of different images with no cohesion between them.  

From the looks of it it's a great model so I think it's quite exciting!

**Comment by continue-revolution** [comment]
wait after tomorrow when I'm done with some stupid administrative stuff

**Comment by Mistermango23** [comment]
Lmao

**Comment by Ainaemaet** [comment]
Thank you! It works amazingly. Now we just need the control-net bits and this is officially the best tool available for t2v i2v gen. 

Ooc, is there any way to automate the process of taking the last frame of a given gif (the last png in the sequence) and automatic continuing the generation through img2vid for longer videos??

Thank you again for doing all you are doing here. I am in absolute awe at what I can produce with this. :)   Very excited to share some of what I've done!!

**Comment by continue-revolution** [comment]
@Ainaemaet Wait until I support cli and improve i2gif, before that I have to work on some real life stuff. Please submit a new feature request. I won’t remember checking a closed issue unless someone comment and I receive an email.

**Comment by Ainaemaet** [comment]
@continue-revolution Ok, was just about to make one but I see it's there now - thanks for that.

Yes, please by all means take care of what's most important in your life first!!
