### ISSUE TITLE
[Feature]: SDXL Support

### ISSUE THREAD

**Issue by fuleinist** [continue-revolution/sd-webui-animatediff#82]
### Expected behavior

SDXL is out for a while, any plan to support it? Thx!

**Comment by continue-revolution** [comment]
@guoyww

**Comment by continue-revolution** [comment]
https://github.com/hotshotco/hotshot-xl

I should probably consider supporting this, but it's a long way to go

**Comment by continue-revolution** [comment]
It seems that hotshot has awesome performance, and I will close this for now, and track progress in #224
