### ISSUE TITLE
From the author: the way to resolve generating 2 separate GIFs

### ISSUE THREAD

**Issue by continue-revolution** [continue-revolution/sd-webui-animatediff#83]
You should enable `Pad prompt/negative prompt to be same length` and `Batch cond/uncond` and click `Apply settings` in `Settings`.

For people who are interested in the backend: the reason is that when the `cond` and `uncond` have different shape, WebUI will by-default not batch them because it can't, unless you enable padding.

**Comment by jasoncow007** [comment]
same issue，error report as bellow

2023-09-13 15:58:31,169 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from D:\sd-webui-aki-v4\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
*** Error running before_process: D:\sd-webui-aki-v4\extensions\sd-webui-animatediff\scripts\animatediff.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 199, in before_process
        self.inject_motion_modules(p, model)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-animatediff\scripts\animatediff.py", line 130, in inject_motion_modules
        missed_keys = AnimateDiffScript.motion_module.load_state_dict(mm_state_dict)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
        raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
    RuntimeError: Error(s) in loading state_dict for MotionWrapper:

**Comment by continue-revolution** [comment]
@jasoncow007 the extension use hash to check if it is using v2 model. Your download is most likely incomplete. Also, what you are talking about is not related to this issue.

**Comment by AbstractEyes** [comment]
Enabling padding fixed my problem as well.

**Comment by Symbiomatrix** [comment]
@continue-revolution Perhaps you should pin this issue?

**Comment by Jaggelicious** [comment]
So before enabling `Pad prompt/negative prompt to be same length`
I had this issue where 2 different gifs in one go but they look great.
AFTER I enabled `Pad prompt/negative prompt to be same length` I have just a garbled mess and the frames arent at all smooth, it's just different pictures without any interpolation.

Am I missing something?

**Comment by Jaggelicious** [comment]
![Untitled](https://github.com/continue-revolution/sd-webui-animatediff/assets/145630773/a357ef30-8186-4137-a904-5d2720857045)
As an example.

**Comment by AbyssYuan0** [comment]
> You should enable `Pad prompt/negative prompt to be same length` and `Batch cond/uncond` and click `Apply settings` in `Settings`.
> 
> For people who are interested in the backend: the reason is that when the `cond` and `uncond` have different shape, WebUI will by-default not batch them because it can't, unless you enable padding.

Can't find the setting option? Look here, it's in the Optimizations tab

**Comment by Nerual-Dreming** [comment]
#You should enable Pad prompt/negative prompt to be same length and Batch cond/uncond and click Apply settings in Settings.

Yes, it work for me too.

**Comment by Sostay** [comment]
> So before enabling `Pad prompt/negative prompt to be same length` 所以在启用 `Pad prompt/negative prompt to be same length` 之前 I had this issue where 2 different gifs in one go but they look great. 我有这个问题，其中2个不同的gif在一个去，但他们看起来很棒。 AFTER I enabled `Pad prompt/negative prompt to be same length` I have just a garbled mess and the frames arent at all smooth, it's just different pictures without any interpolation. 在我启用 `Pad prompt/negative prompt to be same length` 后，我只是一个乱码混乱和帧不平滑，它只是不同的图片没有任何插值。
> 
> Am I missing something?我是不是漏了什么？

Enable Pad prompt/negative prompt to be same length and Batch cond/uncond
where is the settings？i cant find it anywhre，who can tell me？
