### ISSUE TITLE
[Question]: CrossAttention class in motion_module

### ISSUE THREAD

**Issue by JaredTherriault** [continue-revolution/sd-webui-animatediff#86]
### Expected behavior

Hello, while working on a PR I noticed that VersatileAttention inherits from a redefined CrossAttention in the motion_module.py. Is there a reason it should be redefined as opposed to using the class from ldm.modules.attention? Or could the redefinition be removed in favour of the existing class? I can open a PR for that.

**Comment by continue-revolution** [comment]
They have different interface.  When init, CrossAttention in motion module accept several more params. I also don't like code duplication, but that's necessary.

**Comment by JaredTherriault** [comment]
Thank you for your response! Fair enough.
